export const datasource = 
[
{"en":"Unit 1- E-C: Sentence","zh":"", },
{"en":"1.Working together, our people have done well.","zh":"齐心协力,我国人民取得了巨大成就。", },
{"en":"Our economy is breaking records, with more than 22 million new jobs,","zh":"我国经济正在创下新的纪录,新增工作岗位 2200 万个,", },
{"en":"and the lowest unemployment in 30 years.","zh":"并且创下 30 年来最低的失业率。", },
{"en":"2.Thanks to the continuing boom in technology shares on the stock market,","zh":"由于在证券市场上技术股的不断上升,", },
{"en":"this year the richest have added 5 billion more to their wealth.","zh":"本年度最富人/人群的财产增值了 50 个亿。", },
{"en":"3.As for this type of camera, there may be cheaper ones on the market.","zh":"就这类照相机(而言),市场上可能会有比它更便宜的。", },
{"en":"But when you look at the quality and the design, you'll agree our price is the most favorable.","zh":"但如果你注意一下它的质量和设计, 你会认可我们的价格是最优惠的。", },
{"en":"4.In 1995, the market share of our product was quite small, only 5%.","zh":"在 1995 年,我们产品的市场占有份额/比例很小,只有 5%。在 1999 年,(份额/比例)增加到 20%。", },
{"en":"In 1999, it has increased to 20%. By the year 2005 we expect the figure to go over 50%.","zh":"到 2005 年,我们期望(那数字/份额/比例)会超过 50%。", },
{"en":"5.In the United States, most enterprises are multiproduct firms.","zh":"在美国,大多数企业是多产品的公司。", },
{"en":"For example, American automobile manufacturers are also responsible for","zh":"比如,美国汽车制造商同时也负责", },
{"en":"such diverse products as diesel locomotives, buses, refrigerators, guided missiles, and air conditioners.","zh":"各种其他诸如柴 油机头 、公共汽车 、冰箱 、制导导弹和空调机(的生产)。", },
{"en":"Passage","zh":"", },
{"en":"1.Inflation can have a number of causes. It can be caused by","zh":"通货膨胀可以是由于几方面的原因(引起的)。可以是由于", },
{"en":"rises in the prices of raw materials:","zh":"原料价格上升：", },
{"en":"factories have to pay more for their raw materials,","zh":"工厂不得不为原 料支付更多钱,", },
{"en":"and as a result they have to put up the prices of their products.","zh":"结果它们不得不提高产品的价格。", },
{"en":"2.Large wage rises can lead to inflation, too:","zh":"大幅度工资增长也会导致通货膨胀:", },
{"en":"if workers are paid more, prices go up and the cost of living rises.","zh":"如果工人的报酬增加,物价就会上涨,生活费用也会上升。", },
{"en":"Changes in the value of currency are another cause of inflation.","zh":"货币价值的变化是通货膨胀的另一个原因:", },
{"en":"If the pound goes down in value, then it costs more to import goods from other countries","zh":"假如英镑贬值,那么从其他国家进口货物时 就要多花钱。", },
{"en":"C - E：Sentence","zh":"", },
{"en":"1.将近三倍的油价暴涨导致了两位数的通货膨胀率及全球经济的衰退。","zh":"The near-tripling of oil prices resulted in double-digit inflation and global economic decline.", },
{"en":"2.中美联系现在十分广泛,涉及我们人民生活的各个方面,","zh":"Sino-American ties have become very extensive, affecting all aspects of our people's lives:", },
{"en":"包括商业 、文化 、教育以及我们 的国家安全政策。","zh":"commerce, culture, education and our national security policies.", },
{"en":"3.人们往往希望雇主支付他们高于市场的工资,他们渴望灵活的工作日程,","zh":"People always want employers to pay them above market rates. They seek flexible work schedules.", },
{"en":"他们要求有公司 股票购买权(优先认股权),还要有机会学习。","zh":"They want stock options and a chance to learn.", },
{"en":"4.对我来说,创业时最大的障碍是搞清楚它是否切实可行。","zh":"For me, the biggest hurdle to get the business running was working out whether it would be feasible at all.", },
{"en":"要做到这一点真的很难, 因为我 以前未涉足过这个行业。","zh":"That's really hard to do as I haven't been involved in the industry ever before.", },
{"en":"5.创业或难或易,但守业绝对不是件容易的事。","zh":"Starting a business may or may not be easy, but keeping it running is really not an easy job.", },
{"en":"目前的统计数字表明,有三分之二的新企业 在创办后的头五年里倒闭。","zh":"According to current statistics, in the first five years, two-thirds of new business will fail.", },
{"en":"Passage","zh":"", },
{"en":"1. 一旦确定了你想获得的贷款种类,你必须和有可能愿意贷款给你开办企业的银行、","zh":"Once you determine the type of loan you wish to pursue, you must contact banks, ", },
{"en":"公司、 或者个人接触。","zh":"companies, or individuals that might be willing to loan funds to begin your business."},
{"en":"商业计划非常重要, 因为它提供很多关于你如何运营企业的细节。","zh":"The business plan is very important because it gives many details about how you plan to run the business.", },
{"en":"如果你有了成熟的商业计划,接下来需要安排与投资者面谈。","zh":"Once you have developed a business plan, you need to schedule an interview with the investors whom you will ask to loan money to you.", },
{"en":"2.你应该告诉投资者你要借贷多少资金, 以及你计划怎样使用这些资金。","zh":"You should be able to talk about how much you will need to loan and how you plan to use the funds.", },
{"en":"没有人会把时间 和金钱投资在一个没有潜质的人身上。","zh":"No one wants to invest their time and money in a person who does not have potential.", },
{"en":"你必须向他们展示你是一个与众不同的人,你有能力 替他们赚取更多的利润。","zh":"You need to show them you are special and can make more profits.", },
{"en":"Unit 1 Supplement: E-C:Sentence","zh":"", },
{"en":"1.With grumblings that India is swiping white-collar jobs from Western nations,","zh":"由于有抱怨说印度正在抢走西方国家中的白领工作,", },
{"en":"industry officials say low-skilled jobs in the industry have become politically sensitive.","zh":"工业部门有关官员称,该行业中技术 不高的工作在政治上变得敏感起来。", },
{"en":"2.A study of justice leads naturally to a study of the various legal systems, which of course,","zh":"法学研究自然涉及对各种法律制度的研究,当然", },
{"en":"in turn, leads to the study of government, and finally, to a study of political economy.","zh":"又涉及对政府的研究,最终又引出对政治 经济学的研究。", },
{"en":"3.In my country we think very highly of British textiles.","zh":"在我国,英国纺织品享有很高的声誉。", },
{"en":"British-made materials for men's suits and English worsted and woolen wear generally are very much admired.","zh":"英国产的男装布料和英格兰的精纺毛料和羊毛服 装通常都大受赞赏。", },
{"en":"4.It is important not to be disappointed if you have to compromise between","zh":"如果你不得不在你", },
{"en":"what you would really like to do and what you are capable of doing.","zh":"真正想做的工作和你胜任的工作之间妥协,重要的是不要失望。", },
{"en":"The thing to remember, in whatever job you do, is to do that job to the best of your ability.","zh":"无论 你做什么工作， 都要记住一点， 尽最大能力去做。", },
{"en":"5.We all want bigger profits and higher wages and shorter working hours.。","zh":"我们都想要更大的利润、更高的工资、更短的工作时间", },
{"en":"But to get all these things we need to be more efficient.","zh":"，但要获得这些，我们就得提高 效率。", },
{"en":"To begin with, we ought to invest more money in new machinery.","zh":"第一步,我们应该在新机器设备上投更多的钱", },
{"en":"Passage","zh":"", },
{"en":"One of the biggest problems with huge American corporations is in the manufacturing staff.","zh":"美国大企业的一个大问题是它们的生产部门员工。", },
{"en":"It is overburdened with layer upon layer of management.","zh":"众多的管理层面使它负担过重。", },
{"en":"If anything is to be reported, for instance, a plant manager is supposed to report to a city manager","zh":"例如: 假如要报告一件事,按规定,工厂经理要向城市经理报告", },
{"en":"who reports to a regional manager who reports to a manager of plants who reports to me, the general manager.","zh":",城市经理再向地区经理报告,地区经理再向总厂经理报告,总厂经理再向我 ---- 总经理报告。", },
{"en":"Consequently, the manager of the local plant, who is a long-term friend of mine","zh":"结果是,本地工厂的经理,作为我的老友,", },
{"en":"and whose office is only a few miles from mine, is almost light years away in terms of management reporting channel.","zh":"他的办公室离我的办公室也只有几英里之遥,但在管理报告程序方面,他和我几乎是光年的距离。", },
{"en":"C - E：Sentence","zh":"", },
{"en":"1.我们寻求的是对国际事务感兴趣的应聘者,","zh":"We look for people with an interest in international affairs.", },
{"en":"他们还要愿意到国外与来自不同文化的人共 事。","zh":"They should be willing to work abroad with people from different cultures.", },
{"en":"2.在竞争激烈的就业市场上,要想脱颖而出,人们的压力比以往任何时候都要大。","zh":"There is more pressure than ever in the competitive job market to stand out from the crowd.", },
{"en":"继续深造 是获得额外优势的一种途径。","zh":"Continuing your education is one way to get that extra edge.", },
{"en":"3.该国际风景旅游开发区占地 190 平方公里,风光秀美 、景致万千。","zh":"The International Scenery & Tourism Development Zone, covers an area of 190 sq. km., with beautiful sceneries changing with times.", },
{"en":"“世园会”就建于原“城 市植物园” 的中心,","zh":"The World Garden Expo will be held in the center of the previous City Botanic Garden,", },
{"en":"由 2.46 平方公里的核心园区和 5 平方公里背景区构成。","zh":"covering 2. 46 sq. km. of land as the core area and 5 sq. km. of land as the background zone.", },
{"en":"4.在中国三百万家民营企业中,有 90%以上属于家族所有。","zh":"More than 90% of China's three million private businesses are family owned.", },
{"en":"其中,大部分是按照家族管理的 方式来经营的。","zh":"The majority of them are operated according to a family style of management.", },
{"en":"创建和从事中国民营企业的男性,年龄在 18 到 34 岁之间。","zh":"The men who create and participate in China's private enterprises range in age from 18 to 34.", },
{"en":"5.目前有三股力量正在推动中国经济的增长 ----","zh":"There are currently three forces powering the growth of China's economy ---", },
{"en":"市场 、 民间以及政府。","zh":"the market, the private sector and the government.", },
{"en":"随着民间力量迅 速摆脱种种束缚,","zh":"As the private sector is rapidly shaking off the fetters of conventions,", },
{"en":"一个新的经济格局正在我国出现。","zh":"a new pattern of economy is taking shape in our country.", },
{"en":"Passage","zh":"", },
{"en":"中国的城市化率目前只有37%, 比世界平均水平低13个百分点。","zh":"China's urbanization rate now stands at merely 37%, 13 percentage points lower than the world's average level.", },
{"en":"大力推进城市化,是中国奔向小康社会的历史重任。","zh":"It remains a historical mission for China to accelerate the process of urbanization, which will enable the nation to move towards moderate prosperity.", },
{"en":"市场经济的发展将加速我国的城市化进程,。","zh":"The development of China's market economy will speed up the process of urbanization of our country and", },
{"en":"全方位改变我国的社会结构。","zh":"reshape the social structure in all dimensions.", },
{"en":"加快我国城市化进程可以一举两得,","zh":"The acceleration of China's urbanization will produce the effect of killing two birds with one stone, ", },
{"en":"一方面可以刺激消费者的需求,另一方面可以 扩大投资支出。","zh":"namely working up consumer demand on the one hand, and boosting investment spending on the other."},
{"en":"随着越来越多的农村人口涌进城市,","zh":"With more and more rural residents flocking into cities,", },
{"en":"到 2020 年, 中国的城市化水平将从目前的 37%增长到 50%以上。","zh":"the urbanization level of China will increase from the current ratio of 37% to over 50% by the year 2020.", },
{"en":"Unit 2- E-C: Sentence","zh":"", },
]