export const datasource = 
[
{"en":"Unit 1- E-C: Sentence","zh":"", },
{"en":"1.Working together, our people have done well.","zh":"齐心协力,我国人民取得了巨大成就。", },
{"en":"Our economy is breaking records, with more than 22 million new jobs,","zh":"我国经济正在创下新的纪录,新增工作岗位 2200 万个,", },
{"en":"and the lowest unemployment in 30 years.","zh":"并且创下 30 年来最低的失业率。", },
{"en":"2.Thanks to the continuing boom in technology shares on the stock market,","zh":"由于在证券市场上技术股的不断上升,", },
{"en":"this year the richest have added 5 billion more to their wealth.","zh":"本年度最富人/人群的财产增值了 50 个亿。", },
{"en":"3.As for this type of camera, there may be cheaper ones on the market.","zh":"就这类照相机(而言),市场上可能会有比它更便宜的。", },
{"en":"But when you look at the quality and the design, you'll agree our price is the most favorable.","zh":"但如果你注意一下它的质量和设计, 你会认可我们的价格是最优惠的。", },
{"en":"4.In 1995, the market share of our product was quite small, only 5%.","zh":"在 1995 年,我们产品的市场占有份额/比例很小,只有 5%。在 1999 年,(份额/比例)增加到 20%。", },
{"en":"In 1999, it has increased to 20%. By the year 2005 we expect the figure to go over 50%.","zh":"到 2005 年,我们期望(那数字/份额/比例)会超过 50%。", },
{"en":"5.In the United States, most enterprises are multiproduct firms.","zh":"在美国,大多数企业是多产品的公司。", },
{"en":"For example, American automobile manufacturers are also responsible for","zh":"比如,美国汽车制造商同时也负责", },
{"en":"such diverse products as diesel locomotives, buses, refrigerators, guided missiles, and air conditioners.","zh":"各种其他诸如柴 油机头 、公共汽车 、冰箱 、制导导弹和空调机(的生产)。", },
{"en":"Passage","zh":"", },
{"en":"1.Inflation can have a number of causes. It can be caused by","zh":"通货膨胀可以是由于几方面的原因(引起的)。可以是由于", },
{"en":"rises in the prices of raw materials:","zh":"原料价格上升：", },
{"en":"factories have to pay more for their raw materials,","zh":"工厂不得不为原 料支付更多钱,", },
{"en":"and as a result they have to put up the prices of their products.","zh":"结果它们不得不提高产品的价格。", },
{"en":"2.Large wage rises can lead to inflation, too:","zh":"大幅度工资增长也会导致通货膨胀:", },
{"en":"if workers are paid more, prices go up and the cost of living rises.","zh":"如果工人的报酬增加,物价就会上涨,生活费用也会上升。", },
{"en":"Changes in the value of currency are another cause of inflation.","zh":"货币价值的变化是通货膨胀的另一个原因:", },
{"en":"If the pound goes down in value, then it costs more to import goods from other countries","zh":"假如英镑贬值,那么从其他国家进口货物时 就要多花钱。", },
{"en":"C - E：Sentence","zh":"", },
{"en":"1.将近三倍的油价暴涨导致了两位数的通货膨胀率及全球经济的衰退。","zh":"The near-tripling of oil prices resulted in double-digit inflation and global economic decline.", },
{"en":"2.中美联系现在十分广泛,涉及我们人民生活的各个方面,","zh":"Sino-American ties have become very extensive, affecting all aspects of our people's lives:", },
{"en":"包括商业 、文化 、教育以及我们 的国家安全政策。","zh":"commerce, culture, education and our national security policies.", },
{"en":"3.人们往往希望雇主支付他们高于市场的工资,他们渴望灵活的工作日程,","zh":"People always want employers to pay them above market rates. They seek flexible work schedules.", },
{"en":"他们要求有公司 股票购买权(优先认股权),还要有机会学习。","zh":"They want stock options and a chance to learn.", },
{"en":"4.对我来说,创业时最大的障碍是搞清楚它是否切实可行。","zh":"For me, the biggest hurdle to get the business running was working out whether it would be feasible at all.", },
{"en":"要做到这一点真的很难, 因为我 以前未涉足过这个行业。","zh":"That's really hard to do as I haven't been involved in the industry ever before.", },
{"en":"5.创业或难或易,但守业绝对不是件容易的事。","zh":"Starting a business may or may not be easy, but keeping it running is really not an easy job.", },
{"en":"目前的统计数字表明,有三分之二的新企业 在创办后的头五年里倒闭。","zh":"According to current statistics, in the first five years, two-thirds of new business will fail.", },
{"en":"Passage","zh":"", },
{"en":"1. 一旦确定了你想获得的贷款种类,你必须和有可能愿意贷款给你开办企业的银行、","zh":"Once you determine the type of loan you wish to pursue, you must contact banks, ", },
{"en":"公司、 或者个人接触。","zh":"companies, or individuals that might be willing to loan funds to begin your business."},
{"en":"商业计划非常重要, 因为它提供很多关于你如何运营企业的细节。","zh":"The business plan is very important because it gives many details about how you plan to run the business.", },
{"en":"如果你有了成熟的商业计划,接下来需要安排与投资者面谈。","zh":"Once you have developed a business plan, you need to schedule an interview with the investors whom you will ask to loan money to you.", },
{"en":"2.你应该告诉投资者你要借贷多少资金, 以及你计划怎样使用这些资金。","zh":"You should be able to talk about how much you will need to loan and how you plan to use the funds.", },
{"en":"没有人会把时间 和金钱投资在一个没有潜质的人身上。","zh":"No one wants to invest their time and money in a person who does not have potential.", },
{"en":"你必须向他们展示你是一个与众不同的人,你有能力 替他们赚取更多的利润。","zh":"You need to show them you are special and can make more profits.", },
{"en":"Unit 1 Supplement: E-C:Sentence","zh":"", },
{"en":"1.With grumblings that India is swiping white-collar jobs from Western nations,","zh":"由于有抱怨说印度正在抢走西方国家中的白领工作,", },
{"en":"industry officials say low-skilled jobs in the industry have become politically sensitive.","zh":"工业部门有关官员称,该行业中技术 不高的工作在政治上变得敏感起来。", },
{"en":"2.A study of justice leads naturally to a study of the various legal systems, which of course,","zh":"法学研究自然涉及对各种法律制度的研究,当然", },
{"en":"in turn, leads to the study of government, and finally, to a study of political economy.","zh":"又涉及对政府的研究,最终又引出对政治 经济学的研究。", },
{"en":"3.In my country we think very highly of British textiles.","zh":"在我国,英国纺织品享有很高的声誉。", },
{"en":"British-made materials for men's suits and English worsted and woolen wear generally are very much admired.","zh":"英国产的男装布料和英格兰的精纺毛料和羊毛服 装通常都大受赞赏。", },
{"en":"4.It is important not to be disappointed if you have to compromise between","zh":"如果你不得不在你", },
{"en":"what you would really like to do and what you are capable of doing.","zh":"真正想做的工作和你胜任的工作之间妥协,重要的是不要失望。", },
{"en":"The thing to remember, in whatever job you do, is to do that job to the best of your ability.","zh":"无论 你做什么工作， 都要记住一点， 尽最大能力去做。", },
{"en":"5.We all want bigger profits and higher wages and shorter working hours.。","zh":"我们都想要更大的利润、更高的工资、更短的工作时间", },
{"en":"But to get all these things we need to be more efficient.","zh":"，但要获得这些，我们就得提高 效率。", },
{"en":"To begin with, we ought to invest more money in new machinery.","zh":"第一步,我们应该在新机器设备上投更多的钱", },
{"en":"Passage","zh":"", },
{"en":"One of the biggest problems with huge American corporations is in the manufacturing staff.","zh":"美国大企业的一个大问题是它们的生产部门员工。", },
{"en":"It is overburdened with layer upon layer of management.","zh":"众多的管理层面使它负担过重。", },
{"en":"If anything is to be reported, for instance, a plant manager is supposed to report to a city manager","zh":"例如: 假如要报告一件事,按规定,工厂经理要向城市经理报告", },
{"en":"who reports to a regional manager who reports to a manager of plants who reports to me, the general manager.","zh":",城市经理再向地区经理报告,地区经理再向总厂经理报告,总厂经理再向我 ---- 总经理报告。", },
{"en":"Consequently, the manager of the local plant, who is a long-term friend of mine","zh":"结果是,本地工厂的经理,作为我的老友,", },
{"en":"and whose office is only a few miles from mine, is almost light years away in terms of management reporting channel.","zh":"他的办公室离我的办公室也只有几英里之遥,但在管理报告程序方面,他和我几乎是光年的距离。", },
{"en":"C - E：Sentence","zh":"", },
{"en":"1.我们寻求的是对国际事务感兴趣的应聘者,","zh":"We look for people with an interest in international affairs.", },
{"en":"他们还要愿意到国外与来自不同文化的人共 事。","zh":"They should be willing to work abroad with people from different cultures.", },
{"en":"2.在竞争激烈的就业市场上,要想脱颖而出,人们的压力比以往任何时候都要大。","zh":"There is more pressure than ever in the competitive job market to stand out from the crowd.", },
{"en":"继续深造 是获得额外优势的一种途径。","zh":"Continuing your education is one way to get that extra edge.", },
{"en":"3.该国际风景旅游开发区占地 190 平方公里,风光秀美 、景致万千。","zh":"The International Scenery & Tourism Development Zone, covers an area of 190 sq. km., with beautiful sceneries changing with times.", },
{"en":"“世园会”就建于原“城 市植物园” 的中心,","zh":"The World Garden Expo will be held in the center of the previous City Botanic Garden,", },
{"en":"由 2.46 平方公里的核心园区和 5 平方公里背景区构成。","zh":"covering 2. 46 sq. km. of land as the core area and 5 sq. km. of land as the background zone.", },
{"en":"4.在中国三百万家民营企业中,有 90%以上属于家族所有。","zh":"More than 90% of China's three million private businesses are family owned.", },
{"en":"其中,大部分是按照家族管理的 方式来经营的。","zh":"The majority of them are operated according to a family style of management.", },
{"en":"创建和从事中国民营企业的男性,年龄在 18 到 34 岁之间。","zh":"The men who create and participate in China's private enterprises range in age from 18 to 34.", },
{"en":"5.目前有三股力量正在推动中国经济的增长 ----","zh":"There are currently three forces powering the growth of China's economy ---", },
{"en":"市场 、 民间以及政府。","zh":"the market, the private sector and the government.", },
{"en":"随着民间力量迅 速摆脱种种束缚,","zh":"As the private sector is rapidly shaking off the fetters of conventions,", },
{"en":"一个新的经济格局正在我国出现。","zh":"a new pattern of economy is taking shape in our country.", },
{"en":"Passage","zh":"", },
{"en":"中国的城市化率目前只有37%, 比世界平均水平低13个百分点。","zh":"China's urbanization rate now stands at merely 37%, 13 percentage points lower than the world's average level.", },
{"en":"大力推进城市化,是中国奔向小康社会的历史重任。","zh":"It remains a historical mission for China to accelerate the process of urbanization, which will enable the nation to move towards moderate prosperity.", },
{"en":"市场经济的发展将加速我国的城市化进程,。","zh":"The development of China's market economy will speed up the process of urbanization of our country and", },
{"en":"全方位改变我国的社会结构。","zh":"reshape the social structure in all dimensions.", },
{"en":"加快我国城市化进程可以一举两得,","zh":"The acceleration of China's urbanization will produce the effect of killing two birds with one stone, ", },
{"en":"一方面可以刺激消费者的需求,另一方面可以 扩大投资支出。","zh":"namely working up consumer demand on the one hand, and boosting investment spending on the other."},
{"en":"随着越来越多的农村人口涌进城市,","zh":"With more and more rural residents flocking into cities,", },
{"en":"到 2020 年, 中国的城市化水平将从目前的 37%增长到 50%以上。","zh":"the urbanization level of China will increase from the current ratio of 37% to over 50% by the year 2020.", },
{"en":"Unit 2- E-C: Sentence","zh":"", },

{"en": "1.Water is great medicine, needed to maintain a healthy body, a clear mind,","zh": "水是很好的药物,一个健康的身体 、清醒的头脑", },
{"en": "and a good balance within your tissues. There's more water in your body than anything else,","zh": "和人体组织内的平衡都离不开水 。人体 内水分比其他任何成分都多,", },
{"en": "with every cell containing mostly water. About 60% of your body is water.","zh": "每个细胞主要的成分就是水 。人体的 60%是水。", },
{"en": "2.Dieters are discovering that the kiwi offers twice the orange's vitamin C with one-third the calories,","zh": "节食减肥者发现猕猴桃的维生素 C 含量是橙子的两倍,而热量只有它的三分之一 。", },
{"en": "And since the sweet, delicious kiwi satisfies even a weight-watcher's longing for dessert,","zh": "正因 为甘甜味美的猕猴桃能满足即便是在减肥的人对甜食的渴望,", },
{"en": "dinner may soon replace breakfast as the meal that supplies the family’s daily requirement of vitamin C .","zh": "也许晚餐很快就会代替早餐来 提供家庭每日所需的维生素 C。", },
{"en": "3.Exercise is likewise vital to successful weight loss. Not only does it help burn excess calories,","zh": "锻炼同样对成功的减肥至关重要 。锻炼不仅能帮助燃烧多余的热量,", },
{"en": "but by increasing your physical activity you can modify the way your brain regulates hunger,","zh": "还能通过增加运动 量改善大脑对饥饿的调节,", },
{"en": "in effect making you less susceptible to food cravings.","zh": "实际上让你不会那么容易受食欲的左右。", },
{"en": "4.So let me be clear. Healthcare has changed in recent decades. Outcomes have improved：","zh": "那么让我把话说明白 。近几十年来,医疗得到了改变 。", },
{"en": "such as the higher chance of surviving cancer, in both children and adults, that I mentioned earlier.","zh": "结果证实像我前面提到的儿童和 成人癌症患者存活几率上升 。", },
{"en": "The role and the number of paramedics have expanded so that","zh": "医务护理的角色和数量扩展了,", },
{"en": "no longer is the time taken to get to the hospital the most important thing.","zh": "病人被送到医院所花的时间不再那么最重要了。", },
{"en": "5.We had — the latest numbers indicate that 4. 5million of those kids are actually eligible for Medicaid.","zh": "新数据表明 450 万儿童的确有资格接受医疗援助 。", },
{"en": "Now, most of you here know that when we passed this program we provided for the establishment state-by-state of things","zh": "那么,你们中的大多数知道我们通 过了这个项目,就有条件为一个州接着一个州", },
{"en": " that are called CHIPS, child health insurance programs, to provide health insurance mostly to the children","zh": "设立 CHIPS, 即儿童健康保险项目,来向在工作 中没有健康保险的", },
{"en": "of lower and moderate income working families that don't have health insurance at work.","zh": "低收入和中等收入家庭提供健康保险。", },
{"en": "E-C: Passage","zh": "", },
{"en": "1. To minimize jet lag, first, you need to drink plenty of water. You'd better avoid caffeine. and alcohol as well.","zh": "为了最大限度减轻时差反应,首先,你需要大量饮水 。最好避免咖啡因, 以及酒精(饮料) 。", },
{"en": " Eat lightly during the flight and avoid those high-salt, high-fat entrees the airlines tend to serve.","zh": "在飞行中减少进食,并且避免航空公司往往提供的那种高盐和高脂肪的主食 。", },
{"en": "Food is harder to digest at high altitudes. Sugar isn't helpful either,","zh": "在高空,食品比 较难消化 。糖也是无益的,", },
{"en": "because it sends your blood sugar on a roller-coaster ride.","zh": "因为那会让你的血糖直线上升。", },
{"en": "2. Second, dress comfortably - bring along a pair of sweaters to change into during the flight","zh": "其次，穿着要舒服,带两件在飞行中可换上的毛衣。", },
{"en": "if you don't want to show up at the airport in your Pyjamas.","zh": "假如你不想在机场上穿着睡衣裤出现,", },
{"en": "As soon as the plane takes off , change out of your shoes and into a pair of thin slippers.","zh": " 飞机一起飞,你可马上换双拖鞋 。", },
{"en": "Bring along some juicy fruit to complement your water supply. Try earplugs to shut out the noise.","zh": "带些果汁以增加你的供水量 。用耳塞隔开噪音。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.更保持身体健康,就必须遵循几条规则 。","zh": "In order to maintain good health ,it is important to observe some rules.", },
{"en": "首先,要坚持均衡的饮食,这是我们健康的基础。","zh": "First, it is necessary to stick to a balanced diet, which is the basis of good health.", },
{"en": "2.在过去的一些年中,人们的饮食结构发生了巨大的变化 。","zh": "Great changes have been taking place in people's diet over the past a few years.", },
{"en": "牛奶 、蔬菜和水果逐渐代替了 谷物粮食。","zh": "Milk, fruit and vegetable ate gradually replacing grain.", },
{"en": "3.在中国的很多城市,那些曾经吸引了众多顾客的传统小吃正在渐渐消失 。","zh": "In many cities across China, the traditional snacks, which used to attract lots of customers are now disappearing.", },
{"en": "取而代之的是 时尚的洋快餐店。","zh": "Some traditional snack shops have been replaced by fashionable foreign fast food restaurants", },
{"en": "4.绿色食品是个新名词,它常指那些天然的食品,","zh": "Green food is a new term which often refers to those natural foods.", },
{"en": "因为我们常把自然和绿色联系在一起 。","zh": "It is because of our association of nature with the color green.", },
{"en": "绿色食品是不经过化学处理的,所以它不含任何人工添加的东西。","zh": "The food is not processed chemically, so it does not contain anything that is artificially added to it.", },
{"en": "5.随着社会经济的发展,越来越多的人开始关注他们的健康,节食也变得非常普遍 。","zh": "With the development of social economy, more and more people pay attention to their health and going on a diet becomes very popular.", },
{"en": "节食对 过于肥胖的人来说是非常必要和有益的。","zh": "Dieting is of great necessity and benefit to the over-weighted people .", },
{"en": "C-E Passage","zh": "", },
{"en": "1.快餐的流行是因为我们的生活节奏加快了,快餐店现在随处可见。","zh": "Fast food has become popularized because of the fast paced lifestyles we live. It is now common to find a fast food restaurant everywhere.", },
{"en": "快餐店从鸡趣 、汉堡 到比萨什么都卖。它已成了一个全新的产业。","zh": "They sell everything from chicken wings, burgers to pizzas. This has created an entirely new industry.", },
{"en": "快餐店为那些没有时间好好吃顿饭或长时间在 办公室工作的人提供了服务。","zh": "These restaurants serve people who are too rushed to find the time to eat a proper meal or have to work long hours at the office", },
{"en": "2.随着愈来愈多的城镇都市化,这种趋势仍将继续下去 。","zh": "As more and more cities become urbanized, this trend will continue,", },
{"en": "为了养成良好的饮食习惯,你的目 常饮食应该是丰富多样的 。","zh": "In order to balance your eating habit, you should eat meals from a variety of foods.", },
{"en": "这样你会得到很好的营养以保持身体健康。","zh": "This will give you the proper nutrition your body needs to stay healthy.", },
{"en": "Unit 2 Supplement E-C Sentence","zh": "", },
{"en": "1.Researchers believe they have unlocked the mystery of","zh": "研究人员相信,他们已经能够揭示", },
{"en": "how an antioxidant found in grapes and red wine fights cancer.","zh": "葡萄和红酒中所含的抗氧化剂是如何治疗癌症的 奥秘。", },
{"en": "2.A study concludes that a compound, which acts like an antibiotic to protect grapes from fungus,","zh": "一项研究表明,有一种化合物可以作为抗生素保护葡萄远离真菌,", },
{"en": "may turn off a protein that guards cancer cells from cancer-fighting therapies such as chemotherapy.","zh": "并杀死一种蛋白质,而这种蛋白质可以保护癌细胞免受抗癌疗法影响,例如化疗 。", },
{"en": "The research may one day allow the compound itself to be used in cancer prevention and treatment.","zh": "也许有一天可以将这种化合物用于预防和治疗癌症。", },
{"en": "3.A few years ago, researchers found that the compound kept cells from turning cancerous","zh": "几年前,研究人员就发现这种化合物能够阻止 细胞癌变和肿瘤扩散 。", },
{"en": "and stopped the spread of malignancies.","zh": "肿瘤扩散 。", },
{"en": " The compound also blocked cell inflammation which is linked to arthritis and other diseases.","zh": "同时它还能阻止细 胞发炎,这种炎症可以引发关节炎及其他疾病 。", },
{"en": "The compound can be found in dozens of foods, including mulberries and peanuts.","zh": "许多食物中都含有这种化合物,例如桑甚和花生。", },
{"en": "4.Over the centuries, people's eating habits change from generation to generation.","zh": "几个世纪以来,人们的饮食习惯在一代代改变。", },
{"en": "Before scientists learned about vitamins and other constituents of food, such as proteins andcarbohydrates,","zh": "在科学家们还不知道维生素和食物的其他成分如蛋白质和碳水化合物的时候,", },
{"en": "people believed in eating large quantities of food and were not concerned so much about a balanced diet.","zh": "人们相信应该吃大量的食物,而且不会为平衡的饮食操心。", },
{"en": "5.Asking yourself why you do your job doesn't mean you're dissatisfied, just self-aware.","zh": "问问自己为何你做这项工作并不意味着你对它不满意,而是做到自知之明 。", },
{"en": "This awareness can lead to greater job satisfaction, increased sense of wellbeing and a little more control over what you do,","zh": "这种意识可 以使你获得更大的工作满意度,增加自我满足的程度,更好地把握自己的工作,", },
{"en": "rather than just 'going along for the ride'. For some, it may be time for a change -","zh": "而不仅仅是“ 随 波逐流” 。对有些人来说,可能是改变的时候了", },
{"en": "if so, don't be afraid of it. Change isn't necessarily bad, it's just different.","zh": "——如果这样,不要害怕 。改变不一定是坏事, 只是不同而已 。", },
{"en": "For the rest of us, take a look around, you may find you've got a great view.","zh": "而对于其他人,环顾四周,你会发现风景这边独好。", },
{"en": "E-C: Passage","zh": "", },
{"en": "Most of us have tried at least one quick fix to drop weight for good - fasting,","zh": "我们大多数人都尝试过至少一种长效快速减肥方法", },
{"en": "or eliminating certain foods and nutrients from our diets","zh": "——禁食或者把某些食物和营养从食谱中去掉——", },
{"en": " only to gain the weight back, often packing on even more pounds.","zh": "结果却是反弹,常常弄得比先前还胖。", },
{"en": "So, be suspicious of quick and easy weight loss solutions.","zh": "所以,对快速简单的减肥方法要谨慎。", },
{"en": "The biggest misconception is that doing something in the short term will have long-term results.","zh": "最大的错误概念就是通过短期行为想要获得长远效果。", },
{"en": "While you may want a magic bullet more than anything, fad dieting and gimmicks","zh": "当你想要一颗魔法子弹想得发疯时, 为减肥和 保持身材", },
{"en": "can actually do more harm than good when it comes to losing and maintaining your weight.","zh": "而疯狂节食和用小花招事实上只会对你造成伤害。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.现在,肥胖已成为了一个重要的问题 。","zh": "Nowadays obesity has become a major problem.", },
{"en": "解决肥胖问题唯一的办法是增强体育锻炼并减少 油腻的食物。","zh": "The only solution to the problem of overweight is the increase of physical exercise and decrease of rich food.", },
{"en": "2.医学证明,如果你吸烟,那你得心脏病和其他疾病的几率就会上升。","zh": "Medical science has approved that your chances of having a heart attack and other diseases increase ifyou smoke.", },
{"en": "然而,吸烟的人口还在 不断增长。","zh": "However, the number of people who smoke is still on the rise.", },
{"en": "3.要戒烟不是一件那么容易的事 。","zh": "Getting rid of smoking is not so easy a job.", },
{"en": "那些努力戒烟的人常会经历情绪低落 、","zh": "Those who try to give up smoking often experience depression,", },
{"en": "严重的头痛,有时还会体重大增。","zh": "severe headache and sometimes gain a lot of weight.", },
{"en": "4.美国食品虽然包装讲究 、富有营养,但味道却一年比一年逊色 。","zh": "Although American food is handsomely packaged and nutritious, it tastes less good year by year.", },
{"en": "这就是所谓的科学和经 济学应用到食品生产上的恶果。","zh": "This is the consequence of the so-called science and economics applied in food production", },
{"en": "5.那些宠物爱好者认为宠物能够理解人类并在人们情绪低落时安慰人。","zh": "Pet-lovers think that pets can understand humans and comfort people when they are in low spirit.", },
{"en": "但那些反对饲养宠 物的人认为， 宠物不但污染环境,而且威胁人们的身体健康。","zh": "By contrast, those who are against keeping pets believe that pets not only pollute the environment but also threaten people's health", },
{"en": "C-E Passage","zh": "", },
{"en": "我想对青年人如何保持心理健康提出一些建议 。","zh": "I'd like to give some advice to the young people concerning how to keep healthy psychologically.", },
{"en": "首先,你们应该集中精力投入学习和工作, 以乐观的态度对待生活 。","zh": "First, you should concentrate yourselves on your study and work, and also take an optimistic attitude toward life.", },
{"en": "其次,你们应该与老师 、同学保持良好的关系,与人为善 、尊重他人,时刻准备帮助他人。","zh": "Second, you should remain in good terms with your teachers and fellow students, being well-intentioned and respectful toward others and always ready to help others.", },
{"en": "第三,你们在情感上应该保持轻松 、稳定和愉快 。","zh": "Third, you should be emotionally stable, relaxed and delighted.", },
{"en": "第四,你们必须遵守 法律,遵守公认的道德规范。","zh": "Fourth, you should obey the laws and observe the established codes of ethics.", },
{"en": "第五,你们要言行一致,意志坚强,并公正、客观地评价自己和他人。","zh": "Fifth, you should keep your words consistent with your action, remain strong-willed and evaluate yourselves and others in a just and objective way.", },

{"en": "Unit 3- E-C: Sentence","zh": "", },
{"en": "1.The TV dinner was a frozen meal on a metal tray that people could heat in the micro oven","zh": "都市晚餐是装在金属盘里的冷冻食物,人们可以把它放进微波炉加热", },
{"en": "and eat while they watched TV.","zh": "然后边看电视边 吃 。", },
{"en": "The TV dinner was one of the many time-savers that helped women get out of the kitchen and into the job market.","zh": " 电视晚餐是许多节省时间的方法之一,能帮助女性摆脱厨房进入劳务市场。", },
{"en": "2.Through my mother, I realized the profound importance of living life for myself.","zh": "从我母亲身上我意识到为自己而活的深刻的重要性。", },
{"en": "She never did. She lived her life for me and for her husband. She was the emotional support system for the family.","zh": "她从未为自己活过。她为了我和她 的丈夫而活 。", },
{"en": "She was the thread of continuity. She was who we came home to.","zh": "她是我们家的情感支撑系统 。她是家庭维系的纽带 。她是我们回家的目的,", },
{"en": "She was the reason we venture out again.","zh": "也是我们再次出征的原因。", },
{"en": "3.I've got a new theory about marriage. Two people are in love, they live together,","zh": "我对婚姻有了一种新的理论 。两个人相爱,住到一起,", },
{"en": "and then suddenly one day, they run out of conversation.","zh": "突然有一天,他们和对方无话可说。", },
{"en": "I mean they can't think of a single thing to say to each other. That's it: panic!","zh": "我的意思是他们想不出什么话和对方说。那就是:惊恐!", },
{"en": "Suddenly it occurs to the chap that there is a way out of the deadlock.","zh": "突然这个男的想到有个办法走出这个死结。", },
{"en": "That is: he'll ask her to marry him. And then they've got something to talk about for the rest of their lives.","zh": "那就是:他向她求婚 。这样他们下半辈子就有了谈资。", },
{"en": "4.My mother and father had live their lives in anticipation of the worst scenario, and I had inherited the habit.","zh": "我的父母一辈子都是在预期着将会发生什么最糟的情况中度过的 。", },
{"en": "Money was to be saved for possible future troubles. Life today must be sacrificed for","zh": "我也继承了这种习 惯 。钱得存起来以备将来不时之需 。 今天的生活必须为", },
{"en": "the future because one never knew what tragedy might come.","zh": "将来作出牺牲, 因为谁也不知道会有 怎样的悲剧发生 。", },
{"en": "I remember giving my mother fifteen hundred dollars on her eighty-fourth birthday.","zh": "我记得在母亲 84 岁生日给了她 1500 美元 。", },
{"en": "She refused to spend it,claiming she's put it aside for her old age!","zh": "她拒绝把钱花掉,说存着等老了再花!", },
{"en": "5.In many American homes, family members spend approximately 38 minutes preparing dinner,","zh": "在很多美国家庭中,家庭成员大约花 38 分钟准备晚饭,", },
{"en": "but the average family spends only 26 minutes eating together.","zh": "但平均每个家庭只用 26 分钟一起 吃饭 。", },
{"en": "What's even more surprising is that 27 percent of families spend less than 20 minutes at the dinner table.","zh": "更令人吃惊的是,有 27%的家庭在餐桌边还坐不到 20 分钟 。", },
{"en": "Despite these statistics, there are still several popular mealtime customs that bring a family together,","zh": "尽管有这些统计数据,还 是存在一些流行的用餐习俗让一个家庭聚在一起,", },
{"en": "such as sharing stories about the day's events and","zh": "比如与家人分享一天发生的事情,", },
{"en": "setting aside a special afternoon or evening meal together on weekends.","zh": "在周末特别抽出一个下午或晚上一起吃饭。", },
{"en": "E-C Passage","zh": "", },
{"en": "1. My husband and I married just over a year. But the problems in our relationship have escalated to the point","zh": "我丈夫和我结婚刚满一年,但是我们俩之间的问题已经上升到了", },
{"en": "that it was no longer healthy for us to live together.","zh": "生活在一起不再健康的程度了 。", },
{"en": "Basically he says he gives me all he has to give and it's my problem if that is not good enough.","zh": "他说基本上他给了我他所能给的一切,如果我觉得那还不够好就是我的问题了。", },
{"en": "My sense of security is so unstable in this relationship it is unnatural for me to pretend that everything is okay.","zh": "我对我们的关系如此没有安全感,如果我要装作一切都好是根本不自然的。", },
{"en": "2.He wants me to be positive, uplifting and encouraging every time we talk.","zh": "他要我在每次谈话时态度肯定 、鼓舞 、激励 。", },
{"en": "But I feel like I am setting myself up for more pain.","zh": "但我觉得好像在给自己制造更多的痛苦。", },
{"en": "All the time I am expected to perform my wifely obligations whether I am emotionally present or not.","zh": "不管我的心情怎样我得一直履行妻子的义务 。", },
{"en": "Meanwhile, we find we have less and less time, fewer and fewer topics to talk with.","zh": "同时,我发现我们谈话的时间越来越少,谈论的 话题也越来越少", },
{"en": "C-E: Sentence","zh": "", },
{"en": "1.对中国人来说， 家庭是神圣的的 。 因此中国人","zh": "Families are sacred to the Chinese. Chinese people,", },
{"en": "无论走到哪里都忘不了自己的家庭。","zh": "wherever they may be, will not forget their families.", },
{"en": "2.到了适当的年龄， 家长可以鼓励孩子们去开始过一种独立的生活 。","zh": "Upon reaching an appropriate age, parents may encourage their children to begin an independent life.", },
{"en": "离家之后,孩子们常 常在家庭之外寻找新的社会关系和经济支柱。","zh": "After children leave home they often look for new social relationships and financial support outside the family.", },
{"en": "3.关于什么东西好吃，世界上不同地区的人看法完全不同 。","zh": "People in different parts of the world have completely different ideas about what is good to eat.", },
{"en": "即使他们吃相同的食物，烹制 的方法也往往有很大的差异。","zh": "Even when they eat the same food, they often prepare it very differently.", },
{"en": "4.你赠送给亲戚 、朋友的礼物能够帮助你更好地认识自己 。","zh": "What you give your relatives or friends as presents can help you know yourself better.", },
{"en": "同样,他们赠送给你的礼物也 能告诉你他们的某些个性。","zh": "Also,what they give you can tell you something about their personality.", },
{"en": "5.在其社会化的进程中，孩子应学会照顾自己和独立生活。","zh": "In the process of their socialization, children should learn to take care of themselves and to live independently.", },
{"en": "许多孩子从小就被教会自己做 决定并对自己的行为负责。","zh": "Many children are taught at a very early age to make decisions and be responsible for their actions.", },
{"en": "C-E: Passage","zh": "", },
{"en": "1. 传统上,男性对家庭及家庭成员负有提供经济来源的责任,","zh": "Traditionally the male has been responsible for financial support of the home and family members.", },
{"en": "女性常常负责养儿育女及家务 劳动,","zh": "The female has often been responsible for childraising and housekeeping.", },
{"en": "可是现在在一部分人当中,男性和女性的角色不再固定 。","zh": "However, among some people now, these parental functions are no longer fixed.", },
{"en": "以往男人养家糊口的角色以及妇女作为家庭主妇的角色正在发生变化。","zh": "The traditional role of the man as 'breadwinner' and the woman as housewife is changing.", },
{"en": "2.一些母亲外出工作是因为经济上的需要,其他一些人选择去工作,","zh": "Some mothers work because of a financial need. Others choose to work", },
{"en": "是因为他们觉得家庭的 经济来源应由夫妻双方来分担。","zh": "because they feel that financial support of the family should be shared by the husband and the wife.", },
{"en": "还有一些女性去工作是因为对这种职业自身的兴趣及达成她们","zh": "Still others are motivated to work because of professional interest and", },
{"en": "为社会做贡献的愿望 。 中国现已有超过 50%的妇女成为社会的劳动力。","zh": "a desire to contribute to society. More than 50 percent women are part of the labor force in China.", },
{"en": "Unit 3 Supplement E-C Sentence","zh": "", },
{"en": "1.Most people first realize that they're not so young anymore when they hit their 40s.","zh": "大多数人到了 40 岁才意识到自己年纪不轻了。", },
{"en": "The belly laps over the belt, knees creak, and hair shades to gray.","zh": "小肚腩凸出腰带，膝盖僵硬，头发灰白。", },
{"en": "Vision becomes less acute, strength is sapped, and it's harder to remember names.","zh": "目光不如从前敏锐， 体力日渐衰弱， 有时会想不起别人的名字。", },
{"en": "2.People in their 40s are also setting records for remarriage and blended families.","zh": "40 多岁的人重组家庭的比例突破历史纪录 。", },
{"en": "Some have kids in college and babies in diapers.","zh": "有些人的子女中既有已经上大学的成人， 也有尚在襁褓中的婴儿 。", },
{"en": "Some are juggling custody schedules while others are rearranging empty nests.","zh": "一些人在为子女监护权闹纠纷， 还有一些人正在另觅佳偶。", },
{"en": "3.Analysts say that the advent of two working parents,","zh": "分析家说，双职工父母的出现、", },
{"en": "fewer and 'spoiled' children, increased mobility, materialism and the loss of family","zh": "子女数目减少并被“宠坏” 、人员流动性的增加、物质主义 以及家庭", },
{"en": "and community authority have led to higher lawlessness.","zh": "和社区权威的丧失致使违法行为有增无减。", },
{"en": "4.Well, I suppose we have more freedom of choice and we're more independent,","zh": "我觉得我们的选择更自由，更独立，", },
{"en": "but, you know, some arranged marriages were very successful.","zh": "但是，你知道，一些包办的婚姻也很成功 。", },
{"en": "Women seemed to be more content with their husbands.","zh": "过去女性对丈夫更满意 。", },
{"en": "Besides, there was something rather charming about courtship in the old days.","zh": "另外， 旧时的恋爱有很吸引人的地方。", },
{"en": "5.As women work longer hours, men have more responsibilities and stress at home.","zh": "由于女性的工作时数增加，男性对家庭承担起更多的责任，压力也自然更大。", },
{"en": "Men are spending almost four more hours a week doing housework than they were two decades earlier,","zh": "男性每周干家务的时间比 20 多年前多了几乎 4 个小时", },
{"en": "as women do eight hours less a week,","zh": ",而女性则少了 8 个小 时。", },
{"en": "says sociologist John Robinson.","zh": "社会学家 约翰罗宾逊说，", },
{"en": "E-C Passage","zh": "", },
{"en": "In Britain, many middle-income group families employ 'dailies', and 'dailies' are those people","zh": "在英国，许多中产阶级家庭雇佣“钟点工”。“钟点工”是那些", },
{"en": "who come in during the week to do the cleaning and other house chores for a fixed couple of hours,","zh": "每周有固定的几小时来做打 扫和其他家务的人。", },
{"en": "and in turn, they receive an hourly or weekly payment.","zh": "作为回报他们收取按时或按周计算的工资。", },
{"en": "Many of these families may also have 'au pair' girls from a foreign country.","zh": "许多这样的家庭还雇有国外来的换工的女孩。", },
{"en": "Officially an au pair girl is supposed to live as one of the family, receiving her keep, entertainment and pocket money.","zh": "从官方角度来说，换工女孩作为家庭一员一起生活，拿生活费、有娱乐和 零花钱。", },
{"en": "In return, she should help with the housework and care of any children.","zh": "作为回报，她必须帮助做家务，照看孩子。", },
{"en": "An au pair girl must have at least one day off each week as time to attend English classes,","zh": "换工女孩每周必须至少有一天的休息去上英语课，", },
{"en": "which is, after all, their main reason for being in Britain.","zh": "毕竟这是她们来英国的主要原因。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.以前, 中国人喜欢大家庭,亲戚们住在一起。","zh": "In the old days, Chinese people preferred to live in extended families with relatives living under the same roof.", },
{"en": "现在人们的生活方式发生了很大的变化,","zh": "Now people's life style has changed a great deal.", },
{"en": "但是 人们,对家庭的依恋却依然如故。","zh": "However, the Chinese still have a strong sentimental attachment for their families.", },
{"en": "2.假如你得到一件 自制的礼物,你是幸运的。","zh": "If you receive a homemade gift, you are lucky.", },
{"en": "它可能制作得并不完美,但却体现了很多的爱。","zh": " It may not be made perfect, but it shows a lot of love.", },
{"en": "馈赠者可以说是十分慷慨的, 因为他们献出了时间和感情。","zh": "People who give homemade gifts may be said to be very generous as they've given time and emotion.", },
{"en": "3.婚姻是一个严肃而复杂的话题 。 以前,","zh": "Marriage is a serious and complex topic. In prior days,", },
{"en": "婚姻被认为是一种稳定的关系,但现在离婚率不断 上升。","zh": "marriage was considered a stable relationship, but now the divorce rate has been rising.", },
{"en": "4.日前,加拿大成为继比利时和荷兰之后,世界上第三个使同性婚姻合法化的国家 。","zh": "Canada recently became the third country in the world, after Belgium and the Netherlands,", },
{"en": "新的法 规将准许同性恋夫妇享有相同的合法权益。","zh": "to legalize same sex marriages. The new legislation will grant gay couples the same legal rights.", },
{"en": "5. 几乎在所有的文化中,两个人的婚姻都被当作一件大事,","zh": "In almost every culture in the world, the marriage of two individuals is considered to be an important event,", },
{"en": "要用仪式和庆典来纪念 。","zh": "to be marked with ceremonies and celebrations.", },
{"en": "参与置 办婚礼的人被称作“新人亲友团” 。","zh": "Those who participate in the organization of the wedding are called the bridal party.", },
{"en": "他们由新人的亲戚和密友组成。","zh": "They are composed of the couple's relatives and closest friends.", },
{"en": "C-E: Passage","zh": "", },
{"en": "一个成功的婚姻应当建立在相互尊重、相互理解和相爱的基础上。","zh": "A successful marriage should be based on mutual respect, understanding and love.", },
{"en": "每一个婚姻都是两个 有着不同性格、不同价值观、不同兴趣的个体的结合。","zh": "Every marriage is a joining of two different persons who have different temperaments, different values and different interests.", },
{"en": "这要求双方的理解、容忍和相当的耐 心。","zh": "This requires understanding, tolerance, and often considerable patience on the part of both partners.", },
{"en": "不幸的是很多人没有经过仔细的考虑和准备便走入婚姻状态。","zh": "It is unfortunate that many marriages are entered into without enough thought and preparation.", },
{"en": "很多婚姻建立在外表的吸 引的基础上,这常常是短暂的 。","zh": "Many marriages are based on physical attraction and this is usually temporary.", },
{"en": "缺乏彼此的理解和信任,只能导致夫妻俩最终离婚 。","zh": "Lack of mutual understanding and trust will finally lead couples to divorce.", },
{"en": "牢固的婚 姻能够让已婚的夫妻承受生活的种种巨变 。","zh": "A strong bond will allow a married couple to endure dramatic changes in their lives.", },
{"en": "即使在最困难的情况下,爱情总能让人找到解决问题的办法。","zh": "In the most difficult circumstance, love will always help them find a way out.", },

{"en": "Unit 4- E-C: Sentence","zh": "", },
{"en": "1.After my flight arrived sometime past midnight on Thursday morning, I was in no mood to figure out a strange public transit system, ","zh": "我的航班在星期四凌晨到达后,我没心情去搞懂陌生的公交系统,", },
{"en": "so I shelled out for a taxi to the hotel. On the way there, the worst car accident I've ever seen happened right in front of us.","zh": "于是我花钱雇了出租车前往旅馆 。在路上在我们的正前方我目睹了我所见过的最严重的车祸。", },
{"en": "2.Fresh air -there doesn't seem to be enough of it around any more. At least that's what nonsmokers are ","zh": "我们周围似乎不再有足够的新鲜空气了——至少这是不吸烟者", },
{"en": "claiming as they carry on their fight to breathe freely. ","zh": "继续进行为自由呼吸的斗争中所宣称的。", },
{"en": "Now they can cite you in a court of law if you violate the nonsmoking territories","zh": "如今他们可以 以你侵犯了在 XXXX 而将你告上法庭。", },
{"en": " set aside for them in 'places of public assembly'.","zh": "为不吸烟者设定的非吸烟区  “公共集会场所”  ", },
{"en": "3.Beyond your personal experiences, think about issues that intrigue you. If you're interested, ","zh": "思考一下除了你的个人经历以外的吸引你的问题 。如果你感兴趣,", },
{"en": "doing research and thinking about a subject will be enjoyable and easy.","zh": "做研究和思考某一事 物会让你觉得既简单又有趣。", },
{"en": "Perhaps you can even satisfy your own curiosity as you prepare an article or speech that enlightens someone else.","zh": "也许在你准备一篇启迪别人的文章或演讲的时候 也能同时满足自己的好奇心", },
{"en": "4.At conference registration, we were all given bags full of fliers, a conference schedule, ","zh": "在大会登记处我们拿到了装满广告传单的袋子,里边有一份大会日程", },
{"en": "and some rather inexplicable goodies. The real conference began the next morning. ","zh": "和一些实在无法说清的好东西。大会第二天早上正式开始。", },
{"en": "It's said that the most amazing part about this conference was seeing so many women in one place, and indeed they were everywhere.","zh": "据说这次大会的最惊人的部分是在一个地方看到这么多女性,她们几乎无处不在。", },
{"en": "I doubt anyone will ever get another chance to see 800 female computer scientists in one room.","zh": "我怀疑还有谁能有机会在一间屋子里看到 800 位女电脑专家。", },
{"en": "5.One of the many wonderful things about being a celebrity is the wide variety of people you meet and the things you learn from them. ","zh": "做名人的好处之一是能见到各种各样的人并从他们身上学到东西 。", },
{"en": "For example, I knew very little about embroidery except that I liked it and I thought the people who did it must be very skilful, ","zh": " 比方说, 除了我喜欢刺绣,觉得绣手一定很有技巧、", },
{"en": "clever and patient! So I was  most interested to find out some more. ","zh": "聪明有耐心之外,我对刺绣所知甚少。所以我很有兴趣去发掘。 ", },
{"en": "I understand that, as far back as 770BC, embroidery was an art form practised on silk in China.","zh": "我知道早在公元前 770 年起中国就有了在丝绸上刺绣的艺术形式了。", },
{"en": "E-C Passage","zh": "", },
{"en": "1.Women's fashions tend to change more rapidly and radically than men's. In the early 1900s, ","zh": "女性的时尚往往比男性改变得更快更彻底。在 20 世纪初,", },
{"en": "all women wore their skirts down to the ankle. ","zh": "所有的女性多穿着长及脚踝的裙子 。", },
{"en": "Today, skirt length varies from floor-length to ten inches above the knee. ","zh": "今天,裙子的长度从及地到膝上 10 英寸不等 。", },
{"en": "Women's shoes have also gone through all sorts of changes in the last ninety years.","zh": "过去 90 年里女鞋也经历了各种变化。", },
{"en": "2.For example, boots for women were very common around the turn of the 20th century.Then,  for years, ","zh": "例如,在 20 世纪之交女性穿着靴子十分普遍。然后有好多年,", },
{"en": "they were not considered fashionable. Today they are back in style again in all colors, lengths, and materials.","zh": "它们不再时髦。今天它们又 流行起来了,有各种颜色,长度和材料。", },
{"en": " In fact, today's women can wear all sorts of clothes, even slacks and shorts, on almost any occasion.","zh": "事实上,如今的女性可以穿各种各样的衣服,在大多数场 合,甚至可以穿宽松裤和运动短裤。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.休闲时光将人们从日常工作中解脱出来,有机会找到个人的兴趣 。","zh": "Leisure time provides opportunities for people to find personal interests from the routine of work. ", },
{"en": "然而,工作和娱乐常被 认为是彼此独立的。","zh": "Nevertheless, work and play are usually perceived as separate activities.", },
{"en": "2.利用休闲时光培养一种业余爱好会给我们带来很多回报。","zh": "Using one's leisure time to develop a hobby can bring various rewards. ", },
{"en": "它能给我们带来很多乐趣和朋 友。","zh": "A hobby can provide us with a lot of fun and friends.", },
{"en": "3.在选择一项适合我们个人需要的爱好时,我们通常要考虑一些因素 。","zh": "In choosing a hobby that will suit our individual needs we have to consider several factors.", },
{"en": "我们必须考虑我们 能够在这项爱好上付出的时间和金钱。","zh": "We must consider the amount of free time and money we can spend on it.", },
{"en": "4.可供我们选择的兴趣爱好是很多的 。有些人","zh": "There are a great many hobbies to choose from. Some people ", },
{"en": "喜欢收集钱币和邮票,有些人将他们的业余 时间花在运动和音乐上。","zh": "enjoy collecting coins and stamps, others choose to spend their free time on sports and music.", },
{"en": "5.不同的锻炼形式适合不同的兴趣爱好。","zh": "There are many different forms of exercises to suit different tastes. ", },
{"en": "如有的人喜欢竞技体育,那他可以参加球类运动。 ","zh": "For example, those who enjoy competitive sports may take up ball games. ", },
{"en": "那些喜欢独自运动的人可以跑步或早晚散散步 。","zh": "If they prefer to exercise alone, they can have a  run or take a walkin the morning or evening. ", },
{"en": "无论他们的兴趣是什么,人们总能找到适合他们的运动。","zh": "No matter what their interests are,people can always find the sports that are suitable to them.", },
{"en": "C-E Passage","zh": "", },
{"en": "1. 休闲活动在我们的生活中扮演着越来越重要的角色,主要有以下四方面的原因 。","zh": "Leisure time activities play a more and more important part in our lives. There are four main reasons as follows: ", },
{"en": "首先, 由 于采用新的科学和技术,人们花在工作上的时间比以前要少了 。","zh": "First of all, people spend less time working now than they used to, mostly due to the introduction of new science and technology. ", },
{"en": "普通中国人的工作时间是每周一到周五,早上 9 点到下午 5 点。","zh": "The normal Chinese working time is Monday  to Friday, 9:00 a. m. to 5:00 p. m. ", },
{"en": "第二,大多数工作者每年至少有两个星期的带薪休假,","zh": "Secondly, most working people get a minimum of two weeks' paid holiday a year, ", },
{"en": "有些 职业如教师,假期甚至更多。","zh": "and people in jobs such as teaching even get more.", },
{"en": "2.另外一个原因是, 由于现代医学的发展和生活水平的提高,人们活得更长了 。","zh": "Another reason is that, thanks to the development of modern medicine and higher living standard, people live longer now. ", },
{"en": "这意味着在 退休以后,人们还有很多年的悠闲时光。现在 60 岁以上人口的比例大大提高。","zh": "This means that after retirement, people have quite a few years of leisure left. Nowadays a much higher proportion of the population is over sixty.", },
{"en": "最后,现在每年 出主的孩子比以前要少了,平均每个家庭只有一个孩子 。","zh": "Finally, fewer babies are born each year and the average family in China has only one child. ", },
{"en": "很多已婚妇女出去工作, 即使那些不 出去工作的妇女也有更多的时间来培养各种兴趣爱好, ","zh": "Many married women now go out to work. Even those married women who do not go out to work have more time for various hobbies ", },
{"en": "因为大多数中国家庭都拥有洗衣机、吸尘器及其他一些节省劳力的装置。","zh": "because most Chinese homes now have washing machines, vacum cleaners, and other labor-saving gadgets.", },
{"en": "Unit 4 Supplement E-C Sentence：","zh": "", },
{"en": "1.Smith was a curious human being. He treasured his library, and was continually absorbed in abstractions,","zh": "史密斯是个求知欲很强的人,他将自己的藏书视为珍宝,并一直沉湎于抽象的研究,", },
{"en": " he was notoriously absent-minded.","zh": "是个 出了名的心不在焉的人。", },
{"en": "2.Yoga has become so popular in recent years; it's easy to overlook the fact ","zh": "近年来瑜珈如此受欢迎,很容易让人忽略一个事实,", },
{"en": "that it is actually one of humankind's oldest activities. ","zh": "瑜伽其实是人类最古老的活动之一。 ", },
{"en": "Scholars think that yoga grew out of the methods used by shamans of the Indus Valley, more than 5,000 years ago.","zh": "学者认为瑜珈发源自五千多年前印度河谷里巫师所采用的方法。", },
{"en": "3.Feeling tired? Under too much stress? No time to exercise? Well, you may want to try yoga. ","zh": "累了吗?压力太大吗?没空运动?那么,你也许想试试瑜珈 。 ", },
{"en": " It's what more and more people have been turning to to ease the troubles of modern life.","zh": "已经有越来越多的人求助瑜珈 来舒缓现代生活的烦恼 。", },
{"en": "Practically unheard of in the West until 50 years ago, yoga has become one of the most popular health trends around.","zh": "50 年前在西方几乎还没有人听说过瑜珈,可是现在它已经成为世界 各地最流行的健康风潮之一。", },
{"en": "4.Traditionally isolated, Australian winemakers have had to learn on their own. ","zh": "由于传统上处于孤立状态,澳大利亚葡萄酒生产商们不得不靠自学成才 。", },
{"en": "As a result they have a deep appreciation for and understanding of technique — and a flair for innovation.","zh": "这样一来,他们  非常看重 、也非常了解酿酒工艺——而且善于创新 。", },
{"en": "Australians mix grapes, casks and soils with an agility that produces fresh, dynamic wines.","zh": "澳大利亚人用灵活机动的方式把葡萄、 酒桶和泥土放在一起,酿造出新鲜 、强劲的葡萄酒。", },
{"en": "5.Real estate has long been a source of private wealth. Indeed, some of the world's great fortunes ","zh": "房地产不动产长期以来一直是私人财富的一个来源。实际上，世界上一些巨额财产", },
{"en": "have been founded on it, and the wealthy have long viewed residential property as a suitable vehicle for their earnings. ","zh": "就是 建立在它的基础之上的 。 富人长期以来也把房地产看作获得利益的一种恰当的手段 。", },
{"en": "But commercial real estate, as an investment asset class for wealthy private individuals,","zh": "但是， 作为富人私人的投资资产类别，商业性房地产一直落后于", },
{"en": "has long taken a back seat to the stocks, bonds and cash which have","zh": "投资组合的股票 、债券和现金。", },
{"en": " traditionally made up the portfolios of the rich and super-rich.","zh": "传统上构成富翁和超级富翁 ", },
{"en": "E-C Passage","zh": "", },
{"en": "1.A good history course - English, ancient, or medieval history - is one of the most useful trainings for your mind. ","zh": "一 门好的历史课程，无论是英国历史还是古代或中世纪历史，能为你的头脑提供最好的训练。", },
{"en": "In chemistry you learn that standard chemical reactions happen the same way every time. ","zh": "化学让你知道标准的化学反应每次都以同样的方式发生。", },
{"en": "In biology, you learn how the heart pumps, same way every time. We do not learn about an evolving heart, ","zh": "生物让你明白心脏如何以同 样的方式不断跳动。我们并不学习进化中的心脏、", },
{"en": "an evolving cell membrane, or an evolving chemical operation. ","zh": "细胞膜或化学作用。", },
{"en": "We learn nonhistorical science, and that is very misleading. ","zh": "我们学习非历史的科学，而这有很大误导。", },
{"en": "You've got to train your mind to study things that change and interact and change as they interact. That's evolution.","zh": "你得训练自己的头脑去学习变化的相互作用的东西和相互作用后发生 改变的东西 。那才是进化。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.在全中国,街头的羽毛球活动司空见惯,","zh": "Street games of badminton are common all over China and this sport is popular ", },
{"en": "而且这项运动从街头一直到顶级职业圈都受到了 欢迎 。","zh": "from the street right up to the top professional level. ", },
{"en": "这项运动在全世界范围内发展了数百年之久。","zh": "The sport has existed throughout the world for centuries.", },
{"en": "2.一项最近的调查显示十六七岁的人群最热衷于在网上发表个人文章。","zh": "A recent survey shows that those aged 16 to 17 have taken most avidly to personal online publishing. ", },
{"en": "有些人已经开通了 带有一些个人信息的个人网站。","zh": "Some of them have started personal sites with some personal information.", },
{"en": "3.玩“低空跳伞” 的人称,这个活动得到了社会上众多群体的喜爱,","zh": "Practitioners of 'Base Jumping' say that this activity is enjoyed by a large cross-section of     society, ", },
{"en": "从律师和 IT 顾问一直到 管道工和学生,","zh": "from solicitors and IT consultants to plumbers and students. ", },
{"en": "各个年龄层的人都有,甚至还有那些 50 多岁的人。","zh": "People of all ages, even those in their fifties, like this activity.", },
{"en": "4.在乡野之地过上一段时间,呼吸呼吸新鲜空气,会使大自然爱好者从中受益 。","zh": "Nature lovers will benefit from a spell spent breathing the fresh air of the countryside.", },
{"en": "这种休假方 式是完美的, 因为它既具休闲性又很积极。","zh": " This type of holiday is perfect as it is both relaxing and active.", },
{"en": "5.乒乓球既是一项激动人心的运动,又是一种流行的休闲活动 。","zh": "Table tennis is an exciting sport and a popular recreational activity. ", },
{"en": "大多数中国人对乒乓球再 熟悉不过了 。","zh": "Most Chinese will be more than familiar with table tennis. ", },
{"en": "这是一项每每言及便会让人联想到东方的运动 。然而,它却发源于欧洲。","zh": "It is a sport immediately associated with the East. However, it was created by Europeans.", },
{"en": "C-E Passage","zh": "", },
{"en": "1.一个人在闲暇时光喜欢做的事都可以称作爱好。","zh": "A hobby can be anything a person likes to do when he has time to spare. ", },
{"en": "有的人爬山、饲养宠物、搭建模型飞机。 ","zh": "Some people climb mountains, raise pets, or build model planes. ", },
{"en": "还有的人喜欢画画 、参加音乐会或弹奏乐器。","zh": "Others like to paint pictures, attend concerts, or play musical instruments.", },
{"en": "2.人们培养兴趣爱好因为它们能带来乐趣、友谊、知识和松弛的心情。","zh": "People take up hobbies because they bring enjoyment, friendship, knowledge, and relaxation.   ", },
{"en": "业余爱好能使人在 一天劳累的工作后得以放松,可以在工作和玩乐之间提供一个平衡 。","zh": "Hobbies help people relax after a day's hard work, and provide a balance between work and play.", },
{"en": "业余爱好还能给那些退休的人带来乐趣 。","zh": "Hobbies also offer enjoyment for persons who have retired. ", },
{"en": "任何人,无论他的年龄 、职位 、收人,都可以拥有一项有趣的爱好。","zh": "Anyone can have an interesting hobby, regardless of his age, position, or income.", },
{"en": "3.医生发现业余爱好能帮助病人从他们的生理或精神疾病中恢复。","zh": "Doctors have found that hobbies can help patients recover from physical or mental illness.", },
{"en": "兴趣爱好使一些卧床或 坐轮椅的病人有事可做,使他们忘却自己的痛苦 。","zh": "Hobbies give bedridden or wheelchair patients something to do, keeping them from thinking about their pain. ", },
{"en": "所以现在很多医院靠帮助病人培养兴趣爱  好来治疗病人。","zh": "So nowadays many hospitals treat patients by helping them take up some hobbies.", },

{"en": "Unit 5- E-C: Sentence","zh": "", },
{"en": "1.A territory for an animal is a geographical area that an animal chooses to have dominance over.","zh": "动物的领地是动物选择的有统治权的地理区域。", },
{"en": "Animals such as birds and mammals seem to exert control over their territory. ","zh": "像鸟类和哺乳动物似乎控制着它们的领地。", },
{"en": "And they are more aggressive in defending the center, or core, i. e. the central part of their territory ","zh": "它们在保卫中心或核心，即领地的中心区的时候更加具有攻击性，", },
{"en": "and they become less aggressive in the outer limits of their territory.","zh": "而在领地的边缘地带， 它们的攻击性则有所减弱。", },
{"en": "2.All the plants and animals that live in the desert have adapted amazingly to this lack of water.","zh": "所有生长在沙漠里的动植物都惊人地适应缺水 。", },
{"en": "For example, a typical and well-known desert plant is the cactus. ","zh": "典型的众所周知的沙漠植物是仙人掌。 ", },
{"en": "A cactus has shallow roots that grow over a wide area, so that it can pick up as much water as possible. ","zh": "仙人掌扎根范围大而浅,能最大限度地吸收水分 。 ", },
{"en": "Since cacti are without leaves, they lose little water from their surface through evaporation.","zh": "由于仙人掌没有叶子,所以它的表面通过蒸  发而流失的水分极少。", },
{"en": "3.We must take into account the wider investment needs of the region. ","zh": "我们必须将区域的更广泛的投资需求纳入考虑范围。", },
{"en": "Namely the need and opportunities offered by sustainably managing and utilizing the region's natural ","zh": "即由可持续发展地管理和使用区域 的自然和", },
{"en": "or nature-based infrastructure. ","zh": "以自然为本的基础设施带来的需求和机会 。", },
{"en": "And the return on investment possible through rehabilitating and repairing those parts of the ","zh": "我们还要考虑通过重建和维修已被破坏 、退化或至今维护不佳的那部分", },
{"en": "'ecosystem infrastructure' that have been damaged, degraded or until now poorly maintained.","zh": "“生态基础设施”而带来的可能的回报。", },
{"en": "4.One way we can help protect biological diversity, and protect society from the threat of climate change, ","zh": "要保护生物多样性和使社会免受气候变化的威胁，我们能做的事情之一", },
{"en": "is to protect our existing forests and work, where possible, to replant areas that have been deforested. ","zh": "就是保护现存的森林，在被砍伐而有可能重新植被的地方再植树。", },
{"en": "Between 2000 to 2005, the world lost 73,000 square kilometres of forest each year - ","zh": "2000 年到 2005 年间，每年世界失去 73,000 平方公里的森林,", },
{"en": "an area approximately the size of Panama, nearly a quarter the size of Malaysia.","zh": "面积几乎和巴拿马一样大,接近马来西亚的四分之一。", },
{"en": "5.Many of our ecosystems are not just serving the region, but the whole world. Joseph Stiglitz , ","zh": "我们的生态系统很多并不是为某一地区服务的，而是服务整个世界。", },
{"en": "the Nobel prize-winning economist, estimates that the carbon sequestration ","zh": "诺贝尔经济学奖获 得者约瑟夫 ·斯提格利茨估计热带雨林的碳汇", },
{"en": "or carbon soaking value of tropical forests probably equals or exceeds the current level of international aid ","zh": "或碳吸收的价值相当于甚至超过提供给", },
{"en": "being provided to developing countries. ","zh": "发展中国家的国际援助。", },
{"en": "In other words it is the developing world that is being charitable to the developed by freely ","zh": "换句话说，是发展中国家在援助发达国家， 因为发展中国家无偿", },
{"en": "removing large levels of the gases they are producing and which are causing climate change.","zh": "处理了发达国家制造的导致气候变化的高度的废气。", },
{"en": "E-C Passage","zh": "", },
{"en": "1.What about the animals in the desert? How have they adapted to the desert heat? ","zh": "沙漠动物的情况怎样?  它们如何适应沙漠高温?  ", },
{"en": "First, most desert animals come out only at night in order to avoid the extremes in heat. ","zh": "首先，大多数沙漠动物只在夜间出动以 避免绝对高温 。", },
{"en": "Second, these animals try to find shade or burrow into the sand which may serve as protection against heat.","zh": "其次， 这些动物设法寻找阴凉或洞穴钻进沙堆躲避高温。", },
{"en": "2.But how do these animals conserve water? They obviously need water to live. ","zh": "但是它们如何保存水分呢?  显然它们离不开水。", },
{"en": "Well, some animals drink the moisture provided from the morning dew. ","zh": "嗯，有些动物从晨露中得到水分。", },
{"en": "Others like the kangaroo rat never drink water at all. Finally, ","zh": "另一 些像袋鼠就从不饮水 。最后， ", },
{"en": "reptiles such as snakes and lizards have skins that prevent much water from evaporating from their bodies.","zh": "爬行动物如蛇和蜥蜴的皮肤能保持体内大量水分不被蒸发。", },
{"en": "2. C-E Sentence","zh": "", },
{"en": "1.如果我们进入技术新时代而不首先认识到我们对环境所应负的责任,","zh": "If we enter the new age of technology without first realizing our responsibility to the environment, ", },
{"en": "我们将遇到很多危机。","zh": "we will encounter many hazards.", },
{"en": "2.人口爆炸是当今世界最严重的问题之一。","zh": "Population explosion is one of the most serious problems in the world. ", },
{"en": "它会导致自然资源的匮乏、拥挤的城市和高失 业率 。","zh": "It will lead to shortage of natural resources, more crowded cities and high rate of unemployment.", },
{"en": "要解决这些问题， 我们必须采取有效的措施控制生育率。","zh": "To solve all these problems, we must take effective measures to control the birth rate.", },
{"en": "3.有证据表明,一些野生动物会传播病毒给人类 。","zh": "Evidence shows that some wild animals can transmit their virus to human. ", },
{"en": "捕猎和进食野生动物不仅会破环大自然 的平衡， ","zh": "Hunting or eating wild animals not only destroy the balance of nature, ", },
{"en": "而且会有被动物病毒传染的风险。","zh": "but also run the risk of being infected by virus from animals.", },
{"en": "4.一些科学家认为太阳能是唯一能满足全世界巨大需要的能源。","zh": "Some scientists believe that solar energy is the only kind which can meet the world's enormous needs for power.", },
{"en": "最有用的太阳能设备是太阳能电池 。","zh": "The most useful type of solar power equipment is the solar cell. ", },
{"en": "它最大的优势之一是可以做得很小便于携带。","zh": "One of the cell's advantages is that it can be made small enough to carry.", },
{"en": "5.没有树木，土地将很快变成沙漠；没有树木，","zh": "Without trees, the land will soon turn to desert. Without trees, ", },
{"en": "人们将遭受自然灾害，如洪水、沙尘暴等。 ","zh": "man will suffer from natural disasters such as floods and sandstorms. ", },
{"en": "树木给我们提供了一个平衡的生态环境。","zh": "Trees provide us with a ecological balance of the environment.", },
{"en": "C-E Passage","zh": "", },
{"en": "1.中国很多城市面临水资源短缺的问题。","zh": "Many Chinese cities are faced with the problem of water shortage. ", },
{"en": "这是由人口爆炸、经济的发展以及环境的污染所造成的。","zh": "This is caused by population explosion, the growing economy and its pollution. ", },
{"en": "更糟糕的是，很多人并没有意识到问题的严重性，仍然每天浪费很多水。","zh": "And what is worse, many people don't realize the seriousness of the problem and still waste a lot of water every day. ", },
{"en": "众所周知， 除非水资源短缺的问题得以解决，","zh": "It is known to all that it is impossible to develop our economy at a fast speed ", },
{"en": "否则经济不可能快速发展。所以,我们必须立即采取行动。","zh": "unless the water shortage problem  is solved. So immediate action should be taken.", },
{"en": "2.首先，我们应该让每个人都知道水在许多地方已经越来越缺乏，	","zh": "'First of all, we must let everybody know water is becoming more and more scarce in many places'", },
{"en": "我们在日常生活中绝不 应该浪费水 。","zh": "and we should never waste water in our daily life. ", },
{"en": "其次,我们必须实行计划生育政策并采取行动抗击水污染 。","zh": "Secondly, we must practise birth control  policy and take action to fight against water pollution. ", },
{"en": "如果我们每个人每  天都能节约一点水，","zh": "If everyone of us can save just a little water every day, ", },
{"en": "至少我们能够缓解水的紧张状况。","zh": "we will at least relieve the tension of the water shortage. ", },
{"en": "只有当所有的人都能够意识到水资源 短缺的严重性， 水的问题才能够得到解决。","zh": "Only when all the people realize the seriousness of water shortage, can water problem be solved.", },
{"en": "3 Unit 5 Supplement E-C Sentence：","zh": "", },
{"en": "1.The chief scientist in the research group singles out the United States for 'refusing to'","zh": "	研究小组中的首席科学家特别指出仅占世界人口 4%的美国,", },
{"en": "countenance any remedial action now or in the future to curb its own greenhouse gases, ","zh": "其温室气体的排放量占世 界排放量的 20%,但却始终", },
{"en": "which are 20% of the world's total, even though it has only 4% of the population.","zh": "'拒绝在当前或今后采取任何补救措施'。", },
{"en": "2.Blaming avian flu on bird migrations is misleading. ","zh": "把禽流感归咎于鸟类的迁徙是一种误导 。", },
{"en": "And a 'quick fix' of culling migratory birds is certainly not the solution. ","zh": "把宰杀候鸟作为“速效药” 当然不是解决办法。 ", },
{"en": "Traditional methods of control including culling of infected poultry, ","zh": "传统的控制方法包括宰杀已感染的禽类，", },
{"en": "vaccination and trade restrictions may at considerable expense contain the virus ","zh": "打预防针，和限制贸易，这样也许能在花费大量费用的条件下控制病毒， ", },
{"en": "and reduce economic and human consequences.","zh": "并减少经济损失和对人造成的后果。", },
{"en": "3.A bird's plumage is a good indicator of its condition. ","zh": "鸟类的羽毛能很好地反映其身体状况。", },
{"en": "Growing brightly colored feathers in the first place requires the right genes. ","zh": "羽毛色泽鲜艳明亮的前提是健康的基因。", },
{"en": "Maintaining them requires health (i. e. a good immune system)  and grooming. ","zh": "保持羽 毛亮丽不仅要求身体健康(即拥有完善的免疫系统)， 而且也要打扮装饰 。", },
{"en": "In many bird species feather color and position in the pecking order are closely correlated.","zh": "很多鸟类中， 羽毛 的色彩和它们啄食的先后顺序密切相关。", },
{"en": "4.If there really is life elsewhere in the universe, what are the odds of finding it in our lifetime? ","zh": "如果宇宙的其他地方确实存在生命， 那么我们在有生之年找到外星人的可能性有多大? ", },
{"en": "There's plenty of ifs for skeptical scientists to swallow. As some physicists liked to say, ","zh": "对外星生命存在持怀疑态度的科学家们认为，这个问题有太多的“如果”。", },
{"en": "if there are so many extraterrestrials out there, why haven't we heard from them?","zh": "正如一些物理学家 经常说的那样， 如果宇宙中存在许许多多的外星生命,为什么我们至今没有收到他们的任何信息?", },
{"en": "5.Many scientists were slow to see the significance of such research. ","zh": "许多科学家并没有立刻看到这类研究的意义。", },
{"en": "Why worry about the loss of a few IQ points, they argued, ","zh": "他们说，既然接触化学物质的真正威胁是 危及生命的疾病，", },
{"en": "when the real threat of chemical exposure was life-threatening disease? ","zh": "智商稍微下降几个点有什么可担心的呢?  ", },
{"en": "Today, however, a dramatic increase in learning disabilities had forced Environmental Protection Agency officials ","zh": "今天，学习障碍患者的大幅度增加迫使 环境保护局官员", },
{"en": "to acknowledge that they have ignored a much broader problem . ","zh": "承认，他们忽略了一个更大的问题。", },
{"en": "One of every six children in America suffers from problems such as autism, ","zh": "在美国，每 6 名儿童中就有一名 患有孤独症 、", },
{"en": "aggression, dyslexia, and attention deficit hyperactivity disorder.","zh": "心理敌对 、诵读困难和多动症等疾病。", },
{"en": "E-C Passage","zh": "", },
{"en": "1.The wealth of Africa's ecosystems - of the goods and services provided by nature and their contribution to human wellbeing ","zh": "非洲的生态系统带来的财富，即大自然所提供的商品和服务及对人类生活的贡献，", },
{"en": "is the inescapable theme running throughout the report. ","zh": "是贯 穿报告始终的不可避免的主题。", },
{"en": "Take the wetlands of the Zambezi Basin.","zh": "以赞比亚盆地的湿地为例，", },
{"en": " It is estimated that the economic value in terms of crops and agriculture of these wetlands is close to $50 million a year. ","zh": "据估计每年这些湿地的庄稼和农 业的经济价值达近五千万美元。", },
{"en": "The wetlands also have other economic importance. ","zh": "湿地还有其他重要经济地位 。", },
{"en": "Take biodiversity for example and take the gorillas of the Great Lakes Region. ","zh": "以生物多样性为例，如大湖区的大猩猩， ", },
{"en": "It is estimated that tourism linked with gorilla watching now brings in around $20 million a year.","zh": "据估计如今和观赏大猩猩相关的旅游业每年有 2,000 万美元左右的产值。", },
{"en": "4 C-E Sentence:","zh": "", },
{"en": "1.当我们阅读报纸的时候，常常会碰到“污染”这个词。","zh": "When we read newspaper, we often come across the word 'pollution'. ", },
{"en": "一些人指责工业革命，","zh": "Some people like to   lay the blame on the industrial revolution. ", },
{"en": "他们认为物质的进步同时也给人们带来了很多负面的影响。","zh": "They say that material progress has also brought many negative effects on human.", },
{"en": "2.现在， 越来越多的人开始关注自然资源的开采问题 。 ","zh": "Nowadays more and more people begin to care about the exploitation of the natural resources. ", },
{"en": "随着人口和经济的快速增长,","zh": "With the rapid growth of population and economy, ", },
{"en": "我们 现在开来的资源越多, 留给将来的资源就越少。","zh": "the more resources we exploit today, the less there will be left for the future.", },
{"en": "3.在许多国家，政府和科学家们已经采取措施通过废品的再生利用来减少污染、","zh": "In many countries, governments and scientists have taken measures to reduce the pollution ", },
{"en": "节约自然 资源 。","zh": "and save the natural resources by recycling the wastes. ", },
{"en": "可以再生的物质包括纸张 、玻璃 、罐头 、塑料等。","zh": "Substances that can be recycled include  paper, glass, cans, plastics, etc.", },
{"en": "4.我们常常在报纸上看到一些动物种类濒临灭绝。","zh": "We often read in the newspaper that some kinds of animals are dying out. ", },
{"en": "一些科学家认为气候的变化导致了一些 动物的灭绝 。 ","zh": "Some scientists think that some animals become extinct because of changes in climate. ", },
{"en": "当动物们住的地方变热或变冷,而他们又无法适应新的环境时,它们就会死亡。","zh": "When the places they live become hotter or colder and they can't adapt to the new surroundings, they die.", },
{"en": "5.随着城市的发展、杀虫剂的使用和严重的环境污染，","zh": "With the development of cities, the using of insecticide and serious pollution, ", },
{"en": "很多野生动物面临食物危机。","zh": "many of the wild animals now are faced with food crisis. ", },
{"en": "同时， 人类杀戮一些野生动物来获取它们的毛 、皮 、牙齿等 。","zh": "At the same time, man is killing off some species for their fur, skin, teeth, etc. ", },
{"en": "很多野生动物面临灭绝的危险。","zh": "Many wild animals are facing the danger of extinction.", },
{"en": "C-E Passage","zh": "", },
{"en": "1.西藏自治区位于青藏高原的主体部分，海拔高，地理特殊，","zh": "China's Tibet Autonomous Region is situated on the main body of the Qinghai-Tibet Plateau. ", },
{"en": "野生动植物资源、水资源和 矿产资源丰富， ","zh": "With high altitude, unique geographical feature and rich wildlife, water and mineral resources,", },
{"en": "素有“世界屋脊”之称 。","zh": "it has been called the 'Roof of the World'.", },
{"en": "这里不仅是南亚 、东南亚地区的“生态源”， ","zh": " It is not only the 'ecological source' for the areas in South and Southeast Asia, ", },
{"en": "还是中国","zh": "but is also the 'regulating area' of the climate of China and", },
{"en": "乃至东半球气候的“调节区”。","zh": " indeed of the Eastern Hemisphere as a whole.", },
{"en": "2.西藏自治区有着独特的自然生态和地理环境。","zh": "The Tibet Autonomous Region boasts a unique natural, ecology and geographical environment. ", },
{"en": "复杂多样的地形地貌和特殊的","zh": "The complex and varied terrains and landforms as well as the unique type of ", },
{"en": "生态系统类 型,为生物多样性营造了天然乐园。","zh": "ecological system have created a natural paradise for biodiversity.", },
{"en": "3.中国政府高度重视西藏的生态建设与环境保护，	","zh": "The Chinese Government attaches great importance to ecological improvement and environmental protection in Tibet. ", },
{"en": "为加强西藏的生态建设与环境保护，促 进西藏经济的可持续发展，","zh": "It has made tremendous efforts to strengthen ecological improvement and environmental protection work in Tibet, promote the sustainable development of its economy, ", },
{"en": "提高各族人民的生活质量，做出了巨大的努力。改善生态、保护环境的宣传教育广泛开展、深入人心。","zh": "and improve the quality of life of the people of its various ethnic groups. Publicity and education concerning ecological improvement and environmental protection have been widely carried out, winning popular support.", },
{"en": "广播、电视、报纸、互联网等宣传媒体都把","zh": " The media, including radio,television, newspaper, and the Internet, have given wide ", },
{"en": "造林绿化、 保护环境作为重要栏目， 加大宣传报道力度 。 ","zh": "coverage to afforestation, and environmental protection. ", },
{"en": "中央政府的关心 、全国人民的支持, ","zh": "Concern from the Central Government and support from people throughout the country ", },
{"en": "使西藏的生态建设和环境保护事业进入了新的阶段。","zh": "have enabled Tibet to embark upon a new phase in its ecological improvement and environmental protection undertakings.", },

]