export const datasource = 
[
{"en":"Unit 1- E-C: Sentence","zh":"", },
{"en":"1.Working together, our people have done well.","zh":"齐心协力,我国人民取得了巨大成就。", },
{"en":"Our economy is breaking records, with more than 22 million new jobs,","zh":"我国经济正在创下新的纪录,新增工作岗位 2200 万个,", },
{"en":"and the lowest unemployment in 30 years.","zh":"并且创下 30 年来最低的失业率。", },
{"en":"2.Thanks to the continuing boom in technology shares on the stock market,","zh":"由于在证券市场上技术股的不断上升,", },
{"en":"this year the richest have added 5 billion more to their wealth.","zh":"本年度最富人/人群的财产增值了 50 个亿。", },
{"en":"3.As for this type of camera, there may be cheaper ones on the market.","zh":"就这类照相机(而言),市场上可能会有比它更便宜的。", },
{"en":"But when you look at the quality and the design, you'll agree our price is the most favorable.","zh":"但如果你注意一下它的质量和设计, 你会认可我们的价格是最优惠的。", },
{"en":"4.In 1995, the market share of our product was quite small, only 5%.","zh":"在 1995 年,我们产品的市场占有份额/比例很小,只有 5%。在 1999 年,(份额/比例)增加到 20%。", },
{"en":"In 1999, it has increased to 20%. By the year 2005 we expect the figure to go over 50%.","zh":"到 2005 年,我们期望(那数字/份额/比例)会超过 50%。", },
{"en":"5.In the United States, most enterprises are multiproduct firms.","zh":"在美国,大多数企业是多产品的公司。", },
{"en":"For example, American automobile manufacturers are also responsible for","zh":"比如,美国汽车制造商同时也负责", },
{"en":"such diverse products as diesel locomotives, buses, refrigerators, guided missiles, and air conditioners.","zh":"各种其他诸如柴 油机头 、公共汽车 、冰箱 、制导导弹和空调机(的生产)。", },
{"en":"Passage","zh":"", },
{"en":"1.Inflation can have a number of causes. It can be caused by","zh":"通货膨胀可以是由于几方面的原因(引起的)。可以是由于", },
{"en":"rises in the prices of raw materials:","zh":"原料价格上升：", },
{"en":"factories have to pay more for their raw materials,","zh":"工厂不得不为原 料支付更多钱,", },
{"en":"and as a result they have to put up the prices of their products.","zh":"结果它们不得不提高产品的价格。", },
{"en":"2.Large wage rises can lead to inflation, too:","zh":"大幅度工资增长也会导致通货膨胀:", },
{"en":"if workers are paid more, prices go up and the cost of living rises.","zh":"如果工人的报酬增加,物价就会上涨,生活费用也会上升。", },
{"en":"Changes in the value of currency are another cause of inflation.","zh":"货币价值的变化是通货膨胀的另一个原因:", },
{"en":"If the pound goes down in value, then it costs more to import goods from other countries","zh":"假如英镑贬值,那么从其他国家进口货物时 就要多花钱。", },
{"en":"C - E：Sentence","zh":"", },
{"en":"1.将近三倍的油价暴涨导致了两位数的通货膨胀率及全球经济的衰退。","zh":"The near-tripling of oil prices resulted in double-digit inflation and global economic decline.", },
{"en":"2.中美联系现在十分广泛,涉及我们人民生活的各个方面,","zh":"Sino-American ties have become very extensive, affecting all aspects of our people's lives:", },
{"en":"包括商业 、文化 、教育以及我们 的国家安全政策。","zh":"commerce, culture, education and our national security policies.", },
{"en":"3.人们往往希望雇主支付他们高于市场的工资,他们渴望灵活的工作日程,","zh":"People always want employers to pay them above market rates. They seek flexible work schedules.", },
{"en":"他们要求有公司 股票购买权(优先认股权),还要有机会学习。","zh":"They want stock options and a chance to learn.", },
{"en":"4.对我来说,创业时最大的障碍是搞清楚它是否切实可行。","zh":"For me, the biggest hurdle to get the business running was working out whether it would be feasible at all.", },
{"en":"要做到这一点真的很难, 因为我 以前未涉足过这个行业。","zh":"That's really hard to do as I haven't been involved in the industry ever before.", },
{"en":"5.创业或难或易,但守业绝对不是件容易的事。","zh":"Starting a business may or may not be easy, but keeping it running is really not an easy job.", },
{"en":"目前的统计数字表明,有三分之二的新企业 在创办后的头五年里倒闭。","zh":"According to current statistics, in the first five years, two-thirds of new business will fail.", },
{"en":"Passage","zh":"", },
{"en":"1. 一旦确定了你想获得的贷款种类,你必须和有可能愿意贷款给你开办企业的银行、","zh":"Once you determine the type of loan you wish to pursue, you must contact banks, ", },
{"en":"公司、 或者个人接触。","zh":"companies, or individuals that might be willing to loan funds to begin your business."},
{"en":"商业计划非常重要, 因为它提供很多关于你如何运营企业的细节。","zh":"The business plan is very important because it gives many details about how you plan to run the business.", },
{"en":"如果你有了成熟的商业计划,接下来需要安排与投资者面谈。","zh":"Once you have developed a business plan, you need to schedule an interview with the investors whom you will ask to loan money to you.", },
{"en":"2.你应该告诉投资者你要借贷多少资金, 以及你计划怎样使用这些资金。","zh":"You should be able to talk about how much you will need to loan and how you plan to use the funds.", },
{"en":"没有人会把时间 和金钱投资在一个没有潜质的人身上。","zh":"No one wants to invest their time and money in a person who does not have potential.", },
{"en":"你必须向他们展示你是一个与众不同的人,你有能力 替他们赚取更多的利润。","zh":"You need to show them you are special and can make more profits.", },
{"en":"Unit 1 Supplement: E-C:Sentence","zh":"", },
{"en":"1.With grumblings that India is swiping white-collar jobs from Western nations,","zh":"由于有抱怨说印度正在抢走西方国家中的白领工作,", },
{"en":"industry officials say low-skilled jobs in the industry have become politically sensitive.","zh":"工业部门有关官员称,该行业中技术 不高的工作在政治上变得敏感起来。", },
{"en":"2.A study of justice leads naturally to a study of the various legal systems, which of course,","zh":"法学研究自然涉及对各种法律制度的研究,当然", },
{"en":"in turn, leads to the study of government, and finally, to a study of political economy.","zh":"又涉及对政府的研究,最终又引出对政治 经济学的研究。", },
{"en":"3.In my country we think very highly of British textiles.","zh":"在我国,英国纺织品享有很高的声誉。", },
{"en":"British-made materials for men's suits and English worsted and woolen wear generally are very much admired.","zh":"英国产的男装布料和英格兰的精纺毛料和羊毛服 装通常都大受赞赏。", },
{"en":"4.It is important not to be disappointed if you have to compromise between","zh":"如果你不得不在你", },
{"en":"what you would really like to do and what you are capable of doing.","zh":"真正想做的工作和你胜任的工作之间妥协,重要的是不要失望。", },
{"en":"The thing to remember, in whatever job you do, is to do that job to the best of your ability.","zh":"无论 你做什么工作， 都要记住一点， 尽最大能力去做。", },
{"en":"5.We all want bigger profits and higher wages and shorter working hours.。","zh":"我们都想要更大的利润、更高的工资、更短的工作时间", },
{"en":"But to get all these things we need to be more efficient.","zh":"，但要获得这些，我们就得提高 效率。", },
{"en":"To begin with, we ought to invest more money in new machinery.","zh":"第一步,我们应该在新机器设备上投更多的钱", },
{"en":"Passage","zh":"", },
{"en":"One of the biggest problems with huge American corporations is in the manufacturing staff.","zh":"美国大企业的一个大问题是它们的生产部门员工。", },
{"en":"It is overburdened with layer upon layer of management.","zh":"众多的管理层面使它负担过重。", },
{"en":"If anything is to be reported, for instance, a plant manager is supposed to report to a city manager","zh":"例如: 假如要报告一件事,按规定,工厂经理要向城市经理报告", },
{"en":"who reports to a regional manager who reports to a manager of plants who reports to me, the general manager.","zh":",城市经理再向地区经理报告,地区经理再向总厂经理报告,总厂经理再向我 ---- 总经理报告。", },
{"en":"Consequently, the manager of the local plant, who is a long-term friend of mine","zh":"结果是,本地工厂的经理,作为我的老友,", },
{"en":"and whose office is only a few miles from mine, is almost light years away in terms of management reporting channel.","zh":"他的办公室离我的办公室也只有几英里之遥,但在管理报告程序方面,他和我几乎是光年的距离。", },
{"en":"C - E：Sentence","zh":"", },
{"en":"1.我们寻求的是对国际事务感兴趣的应聘者,","zh":"We look for people with an interest in international affairs.", },
{"en":"他们还要愿意到国外与来自不同文化的人共 事。","zh":"They should be willing to work abroad with people from different cultures.", },
{"en":"2.在竞争激烈的就业市场上,要想脱颖而出,人们的压力比以往任何时候都要大。","zh":"There is more pressure than ever in the competitive job market to stand out from the crowd.", },
{"en":"继续深造 是获得额外优势的一种途径。","zh":"Continuing your education is one way to get that extra edge.", },
{"en":"3.该国际风景旅游开发区占地 190 平方公里,风光秀美 、景致万千。","zh":"The International Scenery & Tourism Development Zone, covers an area of 190 sq. km., with beautiful sceneries changing with times.", },
{"en":"“世园会”就建于原“城 市植物园” 的中心,","zh":"The World Garden Expo will be held in the center of the previous City Botanic Garden,", },
{"en":"由 2.46 平方公里的核心园区和 5 平方公里背景区构成。","zh":"covering 2. 46 sq. km. of land as the core area and 5 sq. km. of land as the background zone.", },
{"en":"4.在中国三百万家民营企业中,有 90%以上属于家族所有。","zh":"More than 90% of China's three million private businesses are family owned.", },
{"en":"其中,大部分是按照家族管理的 方式来经营的。","zh":"The majority of them are operated according to a family style of management.", },
{"en":"创建和从事中国民营企业的男性,年龄在 18 到 34 岁之间。","zh":"The men who create and participate in China's private enterprises range in age from 18 to 34.", },
{"en":"5.目前有三股力量正在推动中国经济的增长 ----","zh":"There are currently three forces powering the growth of China's economy ---", },
{"en":"市场 、 民间以及政府。","zh":"the market, the private sector and the government.", },
{"en":"随着民间力量迅 速摆脱种种束缚,","zh":"As the private sector is rapidly shaking off the fetters of conventions,", },
{"en":"一个新的经济格局正在我国出现。","zh":"a new pattern of economy is taking shape in our country.", },
{"en":"Passage","zh":"", },
{"en":"中国的城市化率目前只有37%, 比世界平均水平低13个百分点。","zh":"China's urbanization rate now stands at merely 37%, 13 percentage points lower than the world's average level.", },
{"en":"大力推进城市化,是中国奔向小康社会的历史重任。","zh":"It remains a historical mission for China to accelerate the process of urbanization, which will enable the nation to move towards moderate prosperity.", },
{"en":"市场经济的发展将加速我国的城市化进程,。","zh":"The development of China's market economy will speed up the process of urbanization of our country and", },
{"en":"全方位改变我国的社会结构。","zh":"reshape the social structure in all dimensions.", },
{"en":"加快我国城市化进程可以一举两得,","zh":"The acceleration of China's urbanization will produce the effect of killing two birds with one stone, ", },
{"en":"一方面可以刺激消费者的需求,另一方面可以 扩大投资支出。","zh":"namely working up consumer demand on the one hand, and boosting investment spending on the other."},
{"en":"随着越来越多的农村人口涌进城市,","zh":"With more and more rural residents flocking into cities,", },
{"en":"到 2020 年, 中国的城市化水平将从目前的 37%增长到 50%以上。","zh":"the urbanization level of China will increase from the current ratio of 37% to over 50% by the year 2020.", },
{"en":"Unit 2- E-C: Sentence","zh":"", },

{"en": "1.Water is great medicine, needed to maintain a healthy body, a clear mind,","zh": "水是很好的药物,一个健康的身体 、清醒的头脑", },
{"en": "and a good balance within your tissues. There's more water in your body than anything else,","zh": "和人体组织内的平衡都离不开水 。人体 内水分比其他任何成分都多,", },
{"en": "with every cell containing mostly water. About 61% of your body is water.","zh": "每个细胞主要的成分就是水 。人体的 60%是水。", },
{"en": "2.Dieters are discovering that the kiwi offers twice the orange's vitamin C with one-third the calories,","zh": "节食减肥者发现猕猴桃的维生素 C 含量是橙子的两倍,而热量只有它的三分之一 。", },
{"en": "And since the sweet, delicious kiwi satisfies even a weight-watcher's longing for dessert,","zh": "正因 为甘甜味美的猕猴桃能满足即便是在减肥的人对甜食的渴望,", },
{"en": "dinner may soon replace breakfast as the meal that supplies the family’s daily requirement of vitamin C .","zh": "也许晚餐很快就会代替早餐来 提供家庭每日所需的维生素 C。", },
{"en": "3.Exercise is likewise vital to successful weight loss. Not only does it help burn excess calories,","zh": "锻炼同样对成功的减肥至关重要 。锻炼不仅能帮助燃烧多余的热量,", },
{"en": "but by increasing your physical activity you can modify the way your brain regulates hunger,","zh": "还能通过增加运动 量改善大脑对饥饿的调节,", },
{"en": "in effect making you less susceptible to food cravings.","zh": "实际上让你不会那么容易受食欲的左右。", },
{"en": "4.So let me be clear. Healthcare has changed in recent decades. Outcomes have improved：","zh": "那么让我把话说明白 。近几十年来,医疗得到了改变 。", },
{"en": "such as the higher chance of surviving cancer, in both children and adults, that I mentioned earlier.","zh": "结果证实像我前面提到的儿童和 成人癌症患者存活几率上升 。", },
{"en": "The role and the number of paramedics have expanded so that","zh": "医务护理的角色和数量扩展了,", },
{"en": "no longer is the time taken to get to the hospital the most important thing.","zh": "病人被送到医院所花的时间不再那么最重要了。", },
{"en": "5.We had — the latest numbers indicate that 4. 5million of those kids are actually eligible for Medicaid.","zh": "新数据表明 450 万儿童的确有资格接受医疗援助 。", },
{"en": "Now, most of you here know that when we passed this program we provided for the establishment state-by-state of things","zh": "那么,你们中的大多数知道我们通 过了这个项目,就有条件为一个州接着一个州", },
{"en": " that are called CHIPS, child health insurance programs, to provide health insurance mostly to the children","zh": "设立 CHIPS, 即儿童健康保险项目,来向在工作 中没有健康保险的", },
{"en": "of lower and moderate income working families that don't have health insurance at work.","zh": "低收入和中等收入家庭提供健康保险。", },
{"en": "E-C: Passage","zh": "", },
{"en": "1. To minimize jet lag, first, you need to drink plenty of water. You'd better avoid caffeine. and alcohol as well.","zh": "为了最大限度减轻时差反应,首先,你需要大量饮水 。最好避免咖啡因, 以及酒精(饮料) 。", },
{"en": " Eat lightly during the flight and avoid those high-salt, high-fat entrees the airlines tend to serve.","zh": "在飞行中减少进食,并且避免航空公司往往提供的那种高盐和高脂肪的主食 。", },
{"en": "Food is harder to digest at high altitudes. Sugar isn't helpful either,","zh": "在高空,食品比 较难消化 。糖也是无益的,", },
{"en": "because it sends your blood sugar on a roller-coaster ride.","zh": "因为那会让你的血糖直线上升。", },
{"en": "2. Second, dress comfortably - bring along a pair of sweaters to change into during the flight","zh": "其次，穿着要舒服,带两件在飞行中可换上的毛衣。", },
{"en": "if you don't want to show up at the airport in your Pyjamas.","zh": "假如你不想在机场上穿着睡衣裤出现,", },
{"en": "As soon as the plane takes off , change out of your shoes and into a pair of thin slippers.","zh": " 飞机一起飞,你可马上换双拖鞋 。", },
{"en": "Bring along some juicy fruit to complement your water supply. Try earplugs to shut out the noise.","zh": "带些果汁以增加你的供水量 。用耳塞隔开噪音。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.更保持身体健康,就必须遵循几条规则 。","zh": "In order to maintain good health ,it is important to observe some rules.", },
{"en": "首先,要坚持均衡的饮食,这是我们健康的基础。","zh": "First, it is necessary to stick to a balanced diet, which is the basis of good health.", },
{"en": "2.在过去的一些年中,人们的饮食结构发生了巨大的变化 。","zh": "Great changes have been taking place in people's diet over the past a few years.", },
{"en": "牛奶 、蔬菜和水果逐渐代替了 谷物粮食。","zh": "Milk, fruit and vegetable ate gradually replacing grain.", },
{"en": "3.在中国的很多城市,那些曾经吸引了众多顾客的传统小吃正在渐渐消失 。","zh": "In many cities across China, the traditional snacks, which used to attract lots of customers are now disappearing.", },
{"en": "取而代之的是 时尚的洋快餐店。","zh": "Some traditional snack shops have been replaced by fashionable foreign fast food restaurants", },
{"en": "4.绿色食品是个新名词,它常指那些天然的食品,","zh": "Green food is a new term which often refers to those natural foods.", },
{"en": "因为我们常把自然和绿色联系在一起 。","zh": "It is because of our association of nature with the color green.", },
{"en": "绿色食品是不经过化学处理的,所以它不含任何人工添加的东西。","zh": "The food is not processed chemically, so it does not contain anything that is artificially added to it.", },
{"en": "5.随着社会经济的发展,越来越多的人开始关注他们的健康,节食也变得非常普遍 。","zh": "With the development of social economy, more and more people pay attention to their health and going on a diet becomes very popular.", },
{"en": "节食对 过于肥胖的人来说是非常必要和有益的。","zh": "Dieting is of great necessity and benefit to the over-weighted people .", },
{"en": "C-E Passage","zh": "", },
{"en": "1.快餐的流行是因为我们的生活节奏加快了,快餐店现在随处可见。","zh": "Fast food has become popularized because of the fast paced lifestyles we live. It is now common to find a fast food restaurant everywhere.", },
{"en": "快餐店从鸡趣 、汉堡 到比萨什么都卖。它已成了一个全新的产业。","zh": "They sell everything from chicken wings, burgers to pizzas. This has created an entirely new industry.", },
{"en": "快餐店为那些没有时间好好吃顿饭或长时间在 办公室工作的人提供了服务。","zh": "These restaurants serve people who are too rushed to find the time to eat a proper meal or have to work long hours at the office", },
{"en": "2.随着愈来愈多的城镇都市化,这种趋势仍将继续下去 。","zh": "As more and more cities become urbanized, this trend will continue,", },
{"en": "为了养成良好的饮食习惯,你的目 常饮食应该是丰富多样的 。","zh": "In order to balance your eating habit, you should eat meals from a variety of foods.", },
{"en": "这样你会得到很好的营养以保持身体健康。","zh": "This will give you the proper nutrition your body needs to stay healthy.", },
{"en": "Unit 2 Supplement E-C Sentence","zh": "", },
{"en": "1.Researchers believe they have unlocked the mystery of","zh": "研究人员相信,他们已经能够揭示", },
{"en": "how an antioxidant found in grapes and red wine fights cancer.","zh": "葡萄和红酒中所含的抗氧化剂是如何治疗癌症的 奥秘。", },
{"en": "2.A study concludes that a compound, which acts like an antibiotic to protect grapes from fungus,","zh": "一项研究表明,有一种化合物可以作为抗生素保护葡萄远离真菌,", },
{"en": "may turn off a protein that guards cancer cells from cancer-fighting therapies such as chemotherapy.","zh": "并杀死一种蛋白质,而这种蛋白质可以保护癌细胞免受抗癌疗法影响,例如化疗 。", },
{"en": "The research may one day allow the compound itself to be used in cancer prevention and treatment.","zh": "也许有一天可以将这种化合物用于预防和治疗癌症。", },
{"en": "3.A few years ago, researchers found that the compound kept cells from turning cancerous","zh": "几年前,研究人员就发现这种化合物能够阻止 细胞癌变和肿瘤扩散 。", },
{"en": "and stopped the spread of malignancies.","zh": "肿瘤扩散 。", },
{"en": " The compound also blocked cell inflammation which is linked to arthritis and other diseases.","zh": "同时它还能阻止细 胞发炎,这种炎症可以引发关节炎及其他疾病 。", },
{"en": "The compound can be found in dozens of foods, including mulberries and peanuts.","zh": "许多食物中都含有这种化合物,例如桑甚和花生。", },
{"en": "4.Over the centuries, people's eating habits change from generation to generation.","zh": "几个世纪以来,人们的饮食习惯在一代代改变。", },
{"en": "Before scientists learned about vitamins and other constituents of food, such as proteins andcarbohydrates,","zh": "在科学家们还不知道维生素和食物的其他成分如蛋白质和碳水化合物的时候,", },
{"en": "people believed in eating large quantities of food and were not concerned so much about a balanced diet.","zh": "人们相信应该吃大量的食物,而且不会为平衡的饮食操心。", },
{"en": "5.Asking yourself why you do your job doesn't mean you're dissatisfied, just self-aware.","zh": "问问自己为何你做这项工作并不意味着你对它不满意,而是做到自知之明 。", },
{"en": "This awareness can lead to greater job satisfaction, increased sense of wellbeing and a little more control over what you do,","zh": "这种意识可 以使你获得更大的工作满意度,增加自我满足的程度,更好地把握自己的工作,", },
{"en": "rather than just 'going along for the ride'. For some, it may be time for a change -","zh": "而不仅仅是“ 随 波逐流” 。对有些人来说,可能是改变的时候了", },
{"en": "if so, don't be afraid of it. Change isn't necessarily bad, it's just different.","zh": "——如果这样,不要害怕 。改变不一定是坏事, 只是不同而已 。", },
{"en": "For the rest of us, take a look around, you may find you've got a great view.","zh": "而对于其他人,环顾四周,你会发现风景这边独好。", },
{"en": "E-C: Passage","zh": "", },
{"en": "Most of us have tried at least one quick fix to drop weight for good - fasting,","zh": "我们大多数人都尝试过至少一种长效快速减肥方法", },
{"en": "or eliminating certain foods and nutrients from our diets","zh": "——禁食或者把某些食物和营养从食谱中去掉——", },
{"en": " only to gain the weight back, often packing on even more pounds.","zh": "结果却是反弹,常常弄得比先前还胖。", },
{"en": "So, be suspicious of quick and easy weight loss solutions.","zh": "所以,对快速简单的减肥方法要谨慎。", },
{"en": "The biggest misconception is that doing something in the short term will have long-term results.","zh": "最大的错误概念就是通过短期行为想要获得长远效果。", },
{"en": "While you may want a magic bullet more than anything, fad dieting and gimmicks","zh": "当你想要一颗魔法子弹想得发疯时, 为减肥和 保持身材", },
{"en": "can actually do more harm than good when it comes to losing and maintaining your weight.","zh": "而疯狂节食和用小花招事实上只会对你造成伤害。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.现在,肥胖已成为了一个重要的问题 。","zh": "Nowadays obesity has become a major problem.", },
{"en": "解决肥胖问题唯一的办法是增强体育锻炼并减少 油腻的食物。","zh": "The only solution to the problem of overweight is the increase of physical exercise and decrease of rich food.", },
{"en": "2.医学证明,如果你吸烟,那你得心脏病和其他疾病的几率就会上升。","zh": "Medical science has approved that your chances of having a heart attack and other diseases increase ifyou smoke.", },
{"en": "然而,吸烟的人口还在 不断增长。","zh": "However, the number of people who smoke is still on the rise.", },
{"en": "3.要戒烟不是一件那么容易的事 。","zh": "Getting rid of smoking is not so easy a job.", },
{"en": "那些努力戒烟的人常会经历情绪低落 、","zh": "Those who try to give up smoking often experience depression,", },
{"en": "严重的头痛,有时还会体重大增。","zh": "severe headache and sometimes gain a lot of weight.", },
{"en": "4.美国食品虽然包装讲究 、富有营养,但味道却一年比一年逊色 。","zh": "Although American food is handsomely packaged and nutritious, it tastes less good year by year.", },
{"en": "这就是所谓的科学和经 济学应用到食品生产上的恶果。","zh": "This is the consequence of the so-called science and economics applied in food production", },
{"en": "5.那些宠物爱好者认为宠物能够理解人类并在人们情绪低落时安慰人。","zh": "Pet-lovers think that pets can understand humans and comfort people when they are in low spirit.", },
{"en": "但那些反对饲养宠 物的人认为， 宠物不但污染环境,而且威胁人们的身体健康。","zh": "By contrast, those who are against keeping pets believe that pets not only pollute the environment but also threaten people's health", },
{"en": "C-E Passage","zh": "", },
{"en": "我想对青年人如何保持心理健康提出一些建议 。","zh": "I'd like to give some advice to the young people concerning how to keep healthy psychologically.", },
{"en": "首先,你们应该集中精力投入学习和工作, 以乐观的态度对待生活 。","zh": "First, you should concentrate yourselves on your study and work, and also take an optimistic attitude toward life.", },
{"en": "其次,你们应该与老师 、同学保持良好的关系,与人为善 、尊重他人,时刻准备帮助他人。","zh": "Second, you should remain in good terms with your teachers and fellow students, being well-intentioned and respectful toward others and always ready to help others.", },
{"en": "第三,你们在情感上应该保持轻松 、稳定和愉快 。","zh": "Third, you should be emotionally stable, relaxed and delighted.", },
{"en": "第四,你们必须遵守 法律,遵守公认的道德规范。","zh": "Fourth, you should obey the laws and observe the established codes of ethics.", },
{"en": "第五,你们要言行一致,意志坚强,并公正、客观地评价自己和他人。","zh": "Fifth, you should keep your words consistent with your action, remain strong-willed and evaluate yourselves and others in a just and objective way.", },
{"en": "Unit 3- E-C: Sentence","zh": "", },
{"en": "1.The TV dinner was a frozen meal on a metal tray that people could heat in the micro oven","zh": "都市晚餐是装在金属盘里的冷冻食物,人们可以把它放进微波炉加热", },
{"en": "and eat while they watched TV.","zh": "然后边看电视边 吃 。", },
{"en": "The TV dinner was one of the many time-savers that helped women get out of the kitchen and into the job market.","zh": " 电视晚餐是许多节省时间的方法之一,能帮助女性摆脱厨房进入劳务市场。", },
{"en": "2.Through my mother, I realized the profound importance of living life for myself.","zh": "从我母亲身上我意识到为自己而活的深刻的重要性。", },
{"en": "She never did. She lived her life for me and for her husband. She was the emotional support system for the family.","zh": "她从未为自己活过。她为了我和她 的丈夫而活 。", },
{"en": "She was the thread of continuity. She was who we came home to.","zh": "她是我们家的情感支撑系统 。她是家庭维系的纽带 。她是我们回家的目的,", },
{"en": "She was the reason we venture out again.","zh": "也是我们再次出征的原因。", },
{"en": "3.I've got a new theory about marriage. Two people are in love, they live together,","zh": "我对婚姻有了一种新的理论 。两个人相爱,住到一起,", },
{"en": "and then suddenly one day, they run out of conversation.","zh": "突然有一天,他们和对方无话可说。", },
{"en": "I mean they can't think of a single thing to say to each other. That's it: panic!","zh": "我的意思是他们想不出什么话和对方说。那就是:惊恐!", },
{"en": "Suddenly it occurs to the chap that there is a way out of the deadlock.","zh": "突然这个男的想到有个办法走出这个死结。", },
{"en": "That is: he'll ask her to marry him. And then they've got something to talk about for the rest of their lives.","zh": "那就是:他向她求婚 。这样他们下半辈子就有了谈资。", },
{"en": "4.My mother and father had live their lives in anticipation of the worst scenario, and I had inherited the habit.","zh": "我的父母一辈子都是在预期着将会发生什么最糟的情况中度过的 。", },
{"en": "Money was to be saved for possible future troubles. Life today must be sacrificed for","zh": "我也继承了这种习 惯 。钱得存起来以备将来不时之需 。 今天的生活必须为", },
{"en": " the future because one never knew what tragedy might come.","zh": "将来作出牺牲, 因为谁也不知道会有 怎样的悲剧发生 。", },
{"en": "I remember giving my mother fifteen hundred dollars on her eighty-fourth birthday.","zh": "我记得在母亲 84 岁生日给了她 1500 美元 。", },
{"en": "She refused to spend it,claiming she's put it aside for her old age!","zh": "她拒绝把钱花掉,说存着等老了再花!", },
{"en": "5.In many American homes, family members spend approximately 38 minutes preparing dinner,","zh": "在很多美国家庭中,家庭成员大约花 38 分钟准备晚饭,", },
{"en": "but the average family spends only 26 minutes eating together.","zh": "但平均每个家庭只用 26 分钟一起 吃饭 。", },
{"en": "What's even more surprising is that 27 percent of families spend less than 20 minutes at the dinner table.","zh": "更令人吃惊的是,有 27%的家庭在餐桌边还坐不到 20 分钟 。", },
{"en": "Despite these statistics, there are still several popular mealtime customs that bring a family together,","zh": "尽管有这些统计数据,还 是存在一些流行的用餐习俗让一个家庭聚在一起,", },
{"en": "such as sharing stories about the day's events and","zh": "比如与家人分享一天发生的事情,", },
{"en": "setting aside a special afternoon or evening meal together on weekends.","zh": "在周末特别抽出一个下午或晚上一起吃饭。", },
{"en": "E-C Passage","zh": "", },
{"en": "1. My husband and I married just over a year. But the problems in our relationship have escalated to the point","zh": "我丈夫和我结婚刚满一年,但是我们俩之间的问题已经上升到了", },
{"en": "that it was no longer healthy for us to live together.","zh": "生活在一起不再健康的程度了 。", },
{"en": "Basically he says he gives me all he has to give and it's my problem if that is not good enough.","zh": "他说基本上他给了我他所能给的一切,如果我觉得那还不够好就是我的问题了。", },
{"en": "My sense of security is so unstable in this relationship it is unnatural for me to pretend that everything is okay.","zh": "我对我们的关系如此没有安全感,如果我要装作一切都好是根本不自然的。", },
{"en": "2.He wants me to be positive, uplifting and encouraging every time we talk.","zh": "他要我在每次谈话时态度肯定 、鼓舞 、激励 。", },
{"en": "But I feel like I am setting myself up for more pain.","zh": "但我觉得好像在给自己制造更多的痛苦。", },
{"en": "All the time I am expected to perform my wifely obligations whether I am emotionally present or not.","zh": "不管我的心情怎样我得一直履行妻子的义务 。", },
{"en": "Meanwhile, we find we have less and less time, fewer and fewer topics to talk with.","zh": "同时,我发现我们谈话的时间越来越少,谈论的 话题也越来越少", },
{"en": "C-E: Sentence","zh": "", },
{"en": "1.对中国人来说， 家庭是神圣的的 。 因此中国人","zh": "Families are sacred to the Chinese. Chinese people,", },
{"en": "无论走到哪里都忘不了自己的家庭。","zh": "wherever they may be, will not forget their families.", },
{"en": "2.到了适当的年龄， 家长可以鼓励孩子们去开始过一种独立的生活 。","zh": "Upon reaching an appropriate age, parents may encourage their children to begin an independent life.", },
{"en": "离家之后,孩子们常 常在家庭之外寻找新的社会关系和经济支柱。","zh": "After children leave home they often look for new social relationships and financial support outside the family.", },
{"en": "3.关于什么东西好吃，世界上不同地区的人看法完全不同 。","zh": "People in different parts of the world have completely different ideas about what is good to eat.", },
{"en": "即使他们吃相同的食物，烹制 的方法也往往有很大的差异。","zh": "Even when they eat the same food, they often prepare it very differently.", },
{"en": "4.你赠送给亲戚 、朋友的礼物能够帮助你更好地认识自己 。","zh": "What you give your relatives or friends as presents can help you know yourself better.", },
{"en": "同样,他们赠送给你的礼物也 能告诉你他们的某些个性。","zh": "Also,what they give you can tell you something about their personality.", },
{"en": "5.在其社会化的进程中，孩子应学会照顾自己和独立生活。","zh": "In the process of their socialization, children should learn to take care of themselves and to live independently.", },
{"en": "许多孩子从小就被教会自己做 决定并对自己的行为负责。","zh": "Many children are taught at a very early age to make decisions and be responsible for their actions.", },
{"en": "C-E: Passage","zh": "", },
{"en": "1. 传统上,男性对家庭及家庭成员负有提供经济来源的责任,","zh": "Traditionally the male has been responsible for financial support of the home and family members.", },
{"en": "女性常常负责养儿育女及家务 劳动,","zh": "The female has often been responsible for childraising and housekeeping.", },
{"en": "可是现在在一部分人当中,男性和女性的角色不再固定 。","zh": "However, among some people now, these parental functions are no longer fixed.", },
{"en": "以往男人养家糊口的角色以及妇女作为家庭主妇的角色正在发生变化。","zh": "The traditional role of the man as 'breadwinner' and the woman as housewife is changing.", },
{"en": "2.一些母亲外出工作是因为经济上的需要,其他一些人选择去工作,","zh": "Some mothers work because of a financial need. Others choose to work", },
{"en": "是因为他们觉得家庭的 经济来源应由夫妻双方来分担。","zh": "because they feel that financial support of the family should be shared by the husband and the wife.", },
{"en": "还有一些女性去工作是因为对这种职业自身的兴趣及达成她们","zh": "Still others are motivated to work because of professional interest and", },
{"en": "为社会做贡献的愿望 。 中国现已有超过 50%的妇女成为社会的劳动力。","zh": "a desire to contribute to society. More than 50 percent women are part of the labor force in China.", },
{"en": "Unit 3 Supplement E-C Sentence","zh": "", },
{"en": "1.Most people first realize that they're not so young anymore when they hit their 40s.","zh": "大多数人到了 40 岁才意识到自己年纪不轻了。", },
{"en": "The belly laps over the belt, knees creak, and hair shades to gray.","zh": "小肚腩凸出腰带，膝盖僵硬，头发灰白。", },
{"en": "Vision becomes less acute, strength is sapped, and it's harder to remember names.","zh": "目光不如从前敏锐， 体力日渐衰弱， 有时会想不起别人的名字。", },
{"en": "2.People in their 40s are also setting records for remarriage and blended families.","zh": "40 多岁的人重组家庭的比例突破历史纪录 。", },
{"en": "Some have kids in college and babies in diapers.","zh": "有些人的子女中既有已经上大学的成人， 也有尚在襁褓中的婴儿 。", },
{"en": "Some are juggling custody schedules while others are rearranging empty nests.","zh": "一些人在为子女监护权闹纠纷， 还有一些人正在另觅佳偶。", },
{"en": "3.Analysts say that the advent of two working parents,","zh": "分析家说，双职工父母的出现、", },
{"en": "fewer and 'spoiled' children, increased mobility, materialism and the loss of family","zh": "子女数目减少并被“宠坏” 、人员流动性的增加、物质主义 以及家庭", },
{"en": "and community authority have led to higher lawlessness.","zh": "和社区权威的丧失致使违法行为有增无减。", },
{"en": "4.Well, I suppose we have more freedom of choice and we're more independent,","zh": "我觉得我们的选择更自由，更独立，", },
{"en": "but, you know, some arranged marriages were very successful.","zh": "但是，你知道，一些包办的婚姻也很成功 。", },
{"en": "Women seemed to be more content with their husbands.","zh": "过去女性对丈夫更满意 。", },
{"en": "Besides, there was something rather charming about courtship in the old days.","zh": "另外， 旧时的恋爱有很吸引人的地方。", },
{"en": "5.As women work longer hours, men have more responsibilities and stress at home.","zh": "由于女性的工作时数增加，男性对家庭承担起更多的责任，压力也自然更大。", },
{"en": "Men are spending almost four more hours a week doing housework than they were two decades earlier,","zh": "男性每周干家务的时间比 20 多年前多了几乎 4 个小时", },
{"en": "as women do eight hours less a week,","zh": ",而女性则少了 8 个小 时。", },
{"en": "says sociologist John Robinson.","zh": "社会学家 约翰罗宾逊说，", },
{"en": "E-C Passage","zh": "", },
{"en": "In Britain, many middle-income group families employ 'dailies', and 'dailies' are those people","zh": "在英国，许多中产阶级家庭雇佣“钟点工”。“钟点工”是那些", },
{"en": "who come in during the week to do the cleaning and other house chores for a fixed couple of hours,","zh": "每周有固定的几小时来做打 扫和其他家务的人。", },
{"en": "and in turn, they receive an hourly or weekly payment.","zh": "作为回报他们收取按时或按周计算的工资。", },
{"en": "Many of these families may also have 'au pair' girls from a foreign country.","zh": "许多这样的家庭还雇有国外来的换工的女孩。", },
{"en": "Officially an au pair girl is supposed to live as one of the family, receiving her keep, entertainment and pocket money.","zh": "从官方角度来说，换工女孩作为家庭一员一起生活，拿生活费、有娱乐和 零花钱。", },
{"en": "In return, she should help with the housework and care of any children.","zh": "作为回报，她必须帮助做家务，照看孩子。", },
{"en": "An au pair girl must have at least one day off each week as time to attend English classes,","zh": "换工女孩每周必须至少有一天的休息去上英语课，", },
{"en": "which is, after all, their main reason for being in Britain.","zh": "毕竟这是她们来英国的主要原因。", },
{"en": "C-E Sentence","zh": "", },
{"en": "1.以前, 中国人喜欢大家庭,亲戚们住在一起。","zh": "In the old days, Chinese people preferred to live in extended families with relatives living under the same roof.", },
{"en": "现在人们的生活方式发生了很大的变化,","zh": "Now people's life style has changed a great deal.", },
{"en": "但是 人们,对家庭的依恋却依然如故。","zh": "However, the Chinese still have a strong sentimental attachment for their families.", },
{"en": "2.假如你得到一件 自制的礼物,你是幸运的。","zh": "If you receive a homemade gift, you are lucky.", },
{"en": "它可能制作得并不完美,但却体现了很多的爱。","zh": " It may not be made perfect, but it shows a lot of love.", },
{"en": "馈赠者可以说是十分慷慨的, 因为他们献出了时间和感情。","zh": "People who give homemade gifts may be said to be very generous as they've given time and emotion.", },
{"en": "3.婚姻是一个严肃而复杂的话题 。 以前,","zh": "Marriage is a serious and complex topic. In prior days,", },
{"en": "婚姻被认为是一种稳定的关系,但现在离婚率不断 上升。","zh": "marriage was considered a stable relationship, but now the divorce rate has been rising.", },
{"en": "4.日前,加拿大成为继比利时和荷兰之后,世界上第三个使同性婚姻合法化的国家 。","zh": "Canada recently became the third country in the world, after Belgium and the Netherlands,", },
{"en": "新的法 规将准许同性恋夫妇享有相同的合法权益。","zh": "to legalize same sex marriages. The new legislation will grant gay couples the same legal rights.", },
{"en": "5. 几乎在所有的文化中,两个人的婚姻都被当作一件大事,","zh": "In almost every culture in the world, the marriage of two individuals is considered to be an important event,", },
{"en": "要用仪式和庆典来纪念 。","zh": "to be marked with ceremonies and celebrations.", },
{"en": "参与置 办婚礼的人被称作“新人亲友团” 。","zh": "Those who participate in the organization of the wedding are called the bridal party.", },
{"en": "他们由新人的亲戚和密友组成。","zh": "They are composed of the couple's relatives and closest friends.", },
{"en": "C-E: Passage","zh": "", },
{"en": "一个成功的婚姻应当建立在相互尊重、相互理解和相爱的基础上。","zh": "A successful marriage should be based on mutual respect, understanding and love.", },
{"en": "每一个婚姻都是两个 有着不同性格、不同价值观、不同兴趣的个体的结合。","zh": "Every marriage is a joining of two different persons who have different temperaments, different values and different interests.", },
{"en": "这要求双方的理解、容忍和相当的耐 心。","zh": "This requires understanding, tolerance, and often considerable patience on the part of both partners.", },
{"en": "不幸的是很多人没有经过仔细的考虑和准备便走入婚姻状态。","zh": "It is unfortunate that many marriages are entered into without enough thought and preparation.", },
{"en": "很多婚姻建立在外表的吸 引的基础上,这常常是短暂的 。","zh": "Many marriages are based on physical attraction and this is usually temporary.", },
{"en": "缺乏彼此的理解和信任,只能导致夫妻俩最终离婚 。","zh": "Lack of mutual understanding and trust will finally lead couples to divorce.", },
{"en": "牢固的婚 姻能够让已婚的夫妻承受生活的种种巨变 。","zh": "A strong bond will allow a married couple to endure dramatic changes in their lives.", },
{"en": "即使在最困难的情况下,爱情总能让人找到解决问题的办法。","zh": "In the most difficult circumstance, love will always help them find a way out.", },


]